#!/usr/bin/env python3
"""
Export a nextpnr placement as Vivado LOC/BEL constraints.

WHY
---
Two complementary experiments decompose the openXC7-vs-Vivado gap:

    Vivado place  + nextpnr route   -> isolates the PLACER
    nextpnr place + Vivado route    -> isolates the ROUTER   <-- this script

Measured so far on this design (xc7k325t, OdoCrypt miner):

    yosys netlist + nextpnr place&route    92.36 MHz, 0 unrouted
    yosys netlist + Vivado place           ~91 MHz (being re-verified)
    Vivado netlist + Vivado place&route    162 MHz  (its own synthesis, NUM_MINERS=2)

If Vivado's ROUTER on nextpnr's placement also lands near 92 MHz, then neither
nextpnr component is the bottleneck and the netlist sets the ceiling. If it jumps,
the router is.

HOW
---
json2dcp (RapidWright) is not installed, so instead of building a DCP we emit the
placement as constraints against the SAME netlist Vivado reads:

    yosys JSON --write_verilog--> netlist_for_vivado.v   (read by Vivado)
    yosys JSON --nextpnr------->  placed.json            (NEXTPNR_BEL per cell)

Both sides carry yosys cell names, so the placement can be reattached by name.

NAME MAPPING
------------
nextpnr writes NEXTPNR_BEL as "SITE/BELNAME", e.g. "SLICE_X33Y120/A6LUT" or
"RAMB18_X1Y18/RAMB18E1". Vivado wants these as two separate properties:

    set_property LOC SLICE_X33Y120 [get_cells {x}]
    set_property BEL A6LUT         [get_cells {x}]

Cell names need '.' -> '/' for hierarchy, and Vivado needs braces around names
containing [ ].

CAVEATS
-------
* nextpnr PACKS cells, so its cell set is not identical to the yosys netlist's.
  Cells that do not resolve in Vivado are reported and skipped rather than
  silently dropped -- a low match rate invalidates the experiment.
* BRAM/IO/clocking cells may need different handling; they are emitted the same
  way and Vivado will reject any it cannot honour.

USAGE
    ./nextpnr_placement_to_xdc.py placed.json out.xdc
"""
import json
import re
import sys
from collections import Counter


def main():
    if len(sys.argv) < 3:
        sys.exit(__doc__)
    placed, outfile = sys.argv[1], sys.argv[2]

    d = json.load(open(placed))
    mods = d["modules"]
    top = next((m for m in mods if mods[m].get("attributes", {}).get("top")), list(mods)[0])
    cells = mods[top]["cells"]

    kinds = Counter()
    rows = []
    for name, cell in cells.items():
        bel = cell.get("attributes", {}).get("NEXTPNR_BEL")
        if not bel or "/" not in bel:
            kinds["no-bel"] += 1
            continue
        site, belname = bel.rsplit("/", 1)
        # nextpnr prints hierarchy with '.', Vivado uses '/'. Bus indices stay.
        vname = name.replace(".", "/")
        rows.append((vname, site, belname, cell["type"]))
        kinds[cell["type"]] += 1

    with open(outfile, "w") as f:
        f.write("# nextpnr placement exported as Vivado constraints\n")
        f.write("# generated by nextpnr_placement_to_xdc.py -- do not edit\n")
        f.write("# %d cells\n\n" % len(rows))
        for vname, site, belname, ctype in rows:
            esc = "{%s}" % vname
            f.write("set_property LOC %s [get_cells %s]\n" % (site, esc))
            f.write("set_property BEL %s [get_cells %s]\n" % (belname, esc))

    print("wrote %d placement constraints to %s" % (len(rows), outfile))
    for k, v in kinds.most_common(8):
        print("   %-22s %d" % (k, v))


if __name__ == "__main__":
    main()
