"""Derive the mux4 experiment's wrapper and top from the shipping ones.

DERIVED, NOT EDITED. The shipping RTL is left alone -- a 200MHz bitstream built
from it is flashed and earning right now. Everything the 4-instance experiment
needs that differs is generated into hdl/mux4/ and pulled in only by
build_mux4.tcl.

Generated rather than hand-forked because the shipping wrapper is ~1600 lines
and still changing; a copy edited by hand would drift silently.

NOTE ON LINE ENDINGS. The working tree is CRLF. Reading in universal-newline
mode is what lets the plain-\\n anchors below match at all -- with newline=''
every multi-line anchor silently finds 0 occurrences, which is exactly the trap
that ate several edits earlier today. Written back as CRLF to match the tree.
"""
import io
import os

# Repo-relative -- this file lives in hardware/qmtech-kintex7/tools/.
HDL = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 os.pardir, 'hdl'))
OUT = os.path.join(HDL, 'mux4')

BANNER = """// GENERATED by tools/make_mux4_variants.py -- do not edit by hand.
//
// Derived from ../%s for the 4-instance shared-BRAM experiment.
// The shipping file is untouched; see mux4/miner_mux4.v for what the
// experiment is, what it costs, and why it is an experiment.
//
"""


def rd(path):
    return io.open(path, encoding='utf-8').read()          # universal newlines


def wr(path, s):
    io.open(path, 'w', encoding='utf-8', newline='\r\n').write(s)


def derive(src_name, dst_name, subs, checks):
    src = rd(os.path.join(HDL, src_name))
    for old, new, what in subs:
        n = src.count(old)
        if n != 1:
            raise SystemExit('%s: "%s" matched %d times' % (src_name, what, n))
        src = src.replace(old, new, 1)
    src = (BANNER % src_name) + src
    for pat, what in checks:
        if pat not in src:
            raise SystemExit('%s: post-check failed: %s' % (dst_name, what))
    wr(os.path.join(OUT, dst_name), src)
    print('  wrote mux4/%s' % dst_name)


# ---------------------------------------------------------------- wrapper ---
derive('odocrypt_gpio_wrapper.v', 'odocrypt_gpio_wrapper_mux4.v', [
    ('module odocrypt_gpio_wrapper #(',
     'module odocrypt_gpio_wrapper_mux4 #(', 'module name'),

    # FOUR instances -- the entire point. Each is 210 RAMB18 once muxed, so
    # 4 x 210 = 840 of 890: the same 94% that two stock instances occupy.
    ('    parameter integer NUM_MINERS = 2,',
     '    parameter integer NUM_MINERS = 4,', 'NUM_MINERS'),

    # clk_2x comes from the SAME MMCM as clk_h and is phase-aligned to it, so
    # this is synchronous multi-rate logic, not a clock-domain crossing --
    # no synchronisers between the two.
    ('    input  wire        clk_h,',
     '    input  wire        clk_h,\n'
     '    // 2 x clk_h from the SAME MMCM, phase-aligned. Only the muxed\n'
     '    // S-boxes use it; every other path stays on clk_h.\n'
     '    input  wire        clk_2x,', 'clk_2x port'),

    ('        for (gi = 0; gi < NUM_MINERS; gi = gi + 1) begin : g_miner\n'
     '            miner_pipelined #(',
     '        for (gi = 0; gi < NUM_MINERS; gi = gi + 1) begin : g_miner\n'
     '            miner_pipelined_mux4 #(', 'miner module'),

    ('            ) miner_inst (\n'
     '                .clk   (clk_h),',
     '            ) miner_inst (\n'
     '                .clk   (clk_h),\n'
     '                .clk2x (clk_2x),\n'
     '                .phase (sbox_mux_phase),', 'miner clk2x ports'),
], [
    ('module odocrypt_gpio_wrapper_mux4', 'renamed module'),
    ('NUM_MINERS = 4', 'four instances'),
    ('miner_pipelined_mux4', 'muxed miner'),
])

# The phase register, next to the miner bank.
p = os.path.join(OUT, 'odocrypt_gpio_wrapper_mux4.v')
s = rd(p)
anchor = '    wire [NUM_MINERS-1:0] found_arr;'
if s.count(anchor) != 1:
    raise SystemExit('phase-gen anchor matched %d times' % s.count(anchor))
s = s.replace(anchor,
              "    // ONE phase for the whole design, not one per S-box. Every muxed\n"
              "    // S-box has to interleave identically: two that were out of step\n"
              "    // would drive the same table in the same clk2x window and read\n"
              "    // each other's addresses. Toggling on clk_2x makes it high for\n"
              "    // exactly the half of each clk_h period that serves slot 1.\n"
              "    reg sbox_mux_phase = 1'b0;\n"
              "    always @(posedge clk_2x)\n"
              "        sbox_mux_phase <= ~sbox_mux_phase;\n"
              "\n" + anchor, 1)
wr(p, s)
print('  added the phase generator')

# -------------------------------------------------------------------- top ---
derive('am01_qmtech_top.v', 'am01_qmtech_top_mux4.v', [
    ('module am01_qmtech_top', 'module am01_qmtech_top_mux4', 'module name'),
    ('    odocrypt_gpio_wrapper odocrypt_gpio_wrapper_inst (\n'
     '        .bus_clk   (bus_clk),',
     '    odocrypt_gpio_wrapper_mux4 odocrypt_gpio_wrapper_inst (\n'
     '        .bus_clk   (bus_clk),\n'
     '        .clk_2x    (clk_2x),', 'wrapper instantiation'),
], [
    ('module am01_qmtech_top_mux4', 'renamed top'),
    ('.clk_2x    (clk_2x),', 'clk_2x connected'),
])

# ---------------------------------------------------------------- cmp_256 ---
# The mux4 build can compile NEITHER hdl/odocrypt/encrypt.v (81 of its module
# names collide with encrypt_mux2.v) NOR hdl/odocrypt/miner.v -- miner.v's
# odo_keccak instantiates encrypt_4encrypt with FIVE positional arguments, and
# the muxed core has SEVEN ports (clk2x and phase are the extra two). Leaving
# miner.v in the file set would put a port-count mismatch in the source tree
# even though nothing in this build instantiates odo_keccak.
#
# But cmp_256 is needed, and miner.v is the only place it exists. So lift just
# that module out, carrying the upstream copyright header with it. Extracted by
# line span rather than copied by hand so it tracks upstream if miner.v changes.
src = rd(os.path.join(HDL, os.pardir, os.pardir, os.pardir, 'hdl', 'odocrypt',
                      'miner.v')).split('\n')
end = next(i for i, l in enumerate(src) if l.startswith('endmodule')
           and any(x.startswith('module cmp_256') for x in src[:i]))
head_end = next(i for i, l in enumerate(src) if l.startswith('module cmp_256'))
body = '\n'.join(src[:head_end]) + '\n'
body += ('// EXTRACTED from hdl/odocrypt/miner.v by make_mux4_variants.py.\n'
         '//\n'
         '// cmp_256 alone, because the mux4 build cannot compile miner.v: its\n'
         '// odo_keccak instantiates encrypt_4encrypt with five ports and the\n'
         '// muxed core has seven. Nothing here is modified.\n\n')
body += '\n'.join(src[head_end:end + 1]) + '\n'
wr(os.path.join(OUT, 'cmp_256.v'), body)
print('  wrote mux4/cmp_256.v (%d lines)' % body.count('\n'))
print('done')
