"""Derive the mux4 experiment's wrapper and top from the shipping ones.

DERIVED, NOT EDITED. The shipping RTL is left alone -- a 200MHz bitstream built
from it is flashed and earning right now. Everything the 4-instance experiment
needs that differs is generated into hdl/mux4/ and pulled in only by
build_mux4.tcl.

Generated rather than hand-forked because the shipping wrapper is ~1600 lines
and still changing; a copy edited by hand would drift silently.

NOTE ON LINE ENDINGS. The working tree is CRLF. Reading in universal-newline
mode is what lets the plain-\\n anchors below match at all -- with newline=''
every multi-line anchor silently finds 0 occurrences, which is exactly the trap
that ate several edits earlier today. Written back as CRLF to match the tree.
"""
import io
import os

# Repo-relative -- this file lives in hardware/qmtech-kintex7/tools/.
HDL = os.path.normpath(
    os.path.join(os.path.dirname(os.path.abspath(__file__)),
                 os.pardir, 'hdl'))
OUT = os.path.join(HDL, 'mux4')

BANNER = """// GENERATED by tools/make_mux4_variants.py -- do not edit by hand.
//
// Derived from ../%s for the 4-instance shared-BRAM experiment.
// The shipping file is untouched; see mux4/miner_mux4.v for what the
// experiment is, what it costs, and why it is an experiment.
//
"""


def rd(path):
    return io.open(path, encoding='utf-8').read()          # universal newlines


def wr(path, s):
    io.open(path, 'w', encoding='utf-8', newline='\r\n').write(s)


def derive(src_name, dst_name, subs, checks):
    src = rd(os.path.join(HDL, src_name))
    for old, new, what in subs:
        n = src.count(old)
        if n != 1:
            raise SystemExit('%s: "%s" matched %d times' % (src_name, what, n))
        src = src.replace(old, new, 1)
    src = (BANNER % src_name) + src
    for pat, what in checks:
        if pat not in src:
            raise SystemExit('%s: post-check failed: %s' % (dst_name, what))
    wr(os.path.join(OUT, dst_name), src)
    print('  wrote mux4/%s' % dst_name)


# ---------------------------------------------------------------- wrapper ---
derive('odocrypt_gpio_wrapper.v', 'odocrypt_gpio_wrapper_mux4.v', [
    ('module odocrypt_gpio_wrapper #(',
     'module odocrypt_gpio_wrapper_mux4 #(', 'module name'),

    # FOUR instances -- the entire point. Each is 210 RAMB18 once muxed, so
    # 4 x 210 = 840 of 890: the same 94% that two stock instances occupy.
    ('    parameter integer NUM_MINERS = 2,',
     '    parameter integer NUM_MINERS = 4,', 'NUM_MINERS'),

    # clk_2x comes from the SAME MMCM as clk_h and is phase-aligned to it, so
    # this is synchronous multi-rate logic, not a clock-domain crossing --
    # no synchronisers between the two.
    ('    input  wire        clk_h,',
     '    input  wire        clk_h,\n'
     '    // 2 x clk_h from the SAME MMCM, phase-aligned. Only the muxed\n'
     '    // S-boxes use it; every other path stays on clk_h.\n'
     '    input  wire        clk_2x,', 'clk_2x port'),

    ('        for (gi = 0; gi < NUM_MINERS; gi = gi + 1) begin : g_miner\n'
     '            miner_pipelined #(',
     '        for (gi = 0; gi < NUM_MINERS; gi = gi + 1) begin : g_miner\n'
     '            miner_pipelined_mux4 #(', 'miner module'),
    # found_path refuses NUM_MINERS > 2 by default, because with four cores a
    # cycle where three strobe together discards the third nonce. This build
    # exists to produce a clk_2x WNS figure -- muxed hashrate is exactly
    # clk_2x / 2 -- and a lost nonce does not move a timing number, so the
    # experiment opts in explicitly. It goes HERE rather than in the generated
    # file, which the last attempt proved: a hand edit there is silently
    # removed the next time this runs.
    ('        .SETTLE_CYCLES(SETTLE_CYCLES_P),',
     '        .ALLOW_LOSSY_MULTI_MINER(1),   // EXPERIMENT -- never on a mining build\n'
     '        .SETTLE_CYCLES(SETTLE_CYCLES_P),', 'found_path opt-in'),

    ('            ) miner_inst (\n'
     '                .clk   (clk_h),',
     '            ) miner_inst (\n'
     '                .clk   (clk_h),\n'
     '                .clk2x (clk_2x),\n'
     '                .phase (sbox_mux_phase),', 'miner clk2x ports'),
], [
    ('module odocrypt_gpio_wrapper_mux4', 'renamed module'),
    ('NUM_MINERS = 4', 'four instances'),
    ('miner_pipelined_mux4', 'muxed miner'),
    ('ALLOW_LOSSY_MULTI_MINER', 'found_path experiment opt-in'),
])

# The phase register, next to the miner bank.
p = os.path.join(OUT, 'odocrypt_gpio_wrapper_mux4.v')
s = rd(p)
anchor = '    wire [NUM_MINERS-1:0] found_arr;'
if s.count(anchor) != 1:
    raise SystemExit('phase-gen anchor matched %d times' % s.count(anchor))
s = s.replace(anchor,
              "    // ONE phase for the whole design, not one per S-box. Every muxed\n"
              "    // S-box has to interleave identically: two that were out of step\n"
              "    // would drive the same table in the same clk2x window and read\n"
              "    // each other's addresses. Toggling on clk_2x makes it high for\n"
              "    // exactly the half of each clk_h period that serves slot 1.\n"
              "    reg sbox_mux_phase = 1'b0;\n"
              "    always @(posedge clk_2x)\n"
              "        sbox_mux_phase <= ~sbox_mux_phase;\n"
              "\n" + anchor, 1)
wr(p, s)
print('  added the phase generator')

# -------------------------------------------------------------------- top ---
derive('am01_qmtech_top.v', 'am01_qmtech_top_mux4.v', [
    ('module am01_qmtech_top', 'module am01_qmtech_top_mux4', 'module name'),
    ('    odocrypt_gpio_wrapper odocrypt_gpio_wrapper_inst (\n'
     '        .bus_clk   (bus_clk),',
     '    odocrypt_gpio_wrapper_mux4 odocrypt_gpio_wrapper_inst (\n'
     '        .bus_clk   (bus_clk),\n'
     '        .clk_2x    (clk_2x),', 'wrapper instantiation'),
], [
    ('module am01_qmtech_top_mux4', 'renamed top'),
    ('.clk_2x    (clk_2x),', 'clk_2x connected'),
])

# ---------------------------------------------------------------- cmp_256 ---
# The mux4 build can compile NEITHER hdl/odocrypt/encrypt.v (81 of its module
# names collide with encrypt_mux2.v) NOR hdl/odocrypt/miner.v -- miner.v's
# odo_keccak instantiates encrypt_4encrypt with FIVE positional arguments, and
# the muxed core has SEVEN ports (clk2x and phase are the extra two). Leaving
# miner.v in the file set would put a port-count mismatch in the source tree
# even though nothing in this build instantiates odo_keccak.
#
# But cmp_256 is needed, and miner.v is the only place it exists. So lift just
# that module out, carrying the upstream copyright header with it. Extracted by
# line span rather than copied by hand so it tracks upstream if miner.v changes.
src = rd(os.path.join(HDL, os.pardir, os.pardir, os.pardir, 'hdl', 'odocrypt',
                      'miner.v')).split('\n')
end = next(i for i, l in enumerate(src) if l.startswith('endmodule')
           and any(x.startswith('module cmp_256') for x in src[:i]))
head_end = next(i for i, l in enumerate(src) if l.startswith('module cmp_256'))
body = '\n'.join(src[:head_end]) + '\n'
body += ('// EXTRACTED from hdl/odocrypt/miner.v by make_mux4_variants.py.\n'
         '//\n'
         '// cmp_256 alone, because the mux4 build cannot compile miner.v: its\n'
         '// odo_keccak instantiates encrypt_4encrypt with five ports and the\n'
         '// muxed core has seven. Nothing here is modified.\n\n')
body += '\n'.join(src[head_end:end + 1]) + '\n'
wr(os.path.join(OUT, 'cmp_256.v'), body)

# ---------------------------------------------------------------------
# miner_mux4.v -- the clk2x/phase-carrying miner.
#
# WAS HAND-MAINTAINED, and it cost exactly what hand-maintaining a copy costs:
# the nonce-capture fix landed in miner_pipelined.v on 2026-09-08 and this file
# still had the racy version a day later, with a mux4 build already running
# from it. Generated now, for the same reason the wrapper and top are.
#
# Two sources, because the two modules live in different files: odo_keccak is
# in miner.v and miner_pipelined is in miner_pipelined.v.
ODOCRYPT = os.path.normpath(os.path.join(HDL, os.pardir, os.pardir, os.pardir,
                                         'hdl', 'odocrypt'))


def _extract(path, name):
    """The text of `module <name> ... endmodule`, or die."""
    src = io.open(path, encoding='utf-8').read().replace('\r\n', '\n')
    i = src.find('module ' + name)
    if i < 0:
        raise SystemExit('miner_mux4: no module %s in %s' % (name, path))
    j = src.find('endmodule', i)
    if j < 0:
        raise SystemExit('miner_mux4: unterminated module %s' % name)
    return src[i:j + len('endmodule')]


kec = _extract(os.path.join(ODOCRYPT, 'miner.v'), 'odo_keccak')
mnr = _extract(os.path.join(ODOCRYPT, 'miner_pipelined.v'), 'miner_pipelined')

# odo_keccak -> odo_keccak_mux4: two extra inputs, threaded into the cipher.
kec = kec.replace('module odo_keccak(clk, in, read, target, out, write);',
                  'module odo_keccak_mux4(clk, clk2x, phase, in, read, target,'
                  ' out, write);\n\tinput clk2x;\n\tinput phase;', 1)
kec = kec.replace('encrypt_4encrypt crypt(clk, in, read, midstate, midread);',
                  'encrypt_4encrypt crypt(clk, clk2x, phase, in, read,'
                  ' midstate, midread);', 1)

# miner_pipelined -> miner_pipelined_mux4: same two, threaded into the worker.
mnr = mnr.replace('module miner_pipelined(clk, header, target, nonce, found);',
                  'module miner_pipelined_mux4(clk, clk2x, phase, header,'
                  ' target, nonce, found);', 1)
mnr = mnr.replace('    input clk;',
                  '    input clk;\n    input clk2x;\n    input phase;', 1)
mnr = mnr.replace('odo_keccak worker(clk, {nonce_in, header}, advance, target,'
                  ' res, has_res);',
                  'odo_keccak_mux4 worker(clk, clk2x, phase,'
                  ' {nonce_in, header}, advance,\n'
                  '                           target, res, has_res);', 1)

body = (BANNER % 'odocrypt/miner_pipelined.v + odocrypt/miner.v' +
        '//\n'
        '// The clk2x/phase-carrying variants for the 4-instance shared-BRAM\n'
        '// experiment. Both modules are the shipping ones with two extra input\n'
        '// ports threaded through to encrypt_4encrypt -- nothing else differs,\n'
        '// which is why this is generated rather than copied.\n'
        '//\n'
        '// THROUGHPUT guard, carried over from the hand-written file it\n'
        '// replaced. Without it the `THROUGHPUT references below depend on\n'
        '// some other file having defined it first -- a silent dependency on\n'
        '// compile order. Found by diffing this output against that file.\n'
        '`ifndef THROUGHPUT\n`define THROUGHPUT 4\n`endif\n'
        '\n' + kec + '\n\n' + mnr + '\n')

for want in ('`define THROUGHPUT',
             'odo_keccak_mux4', 'miner_pipelined_mux4', 'clk2x', 'phase',
             'nonce     <= nonce_out;'):
    if want not in body:
        raise SystemExit('miner_mux4: generated file lacks %r' % want)

wr(os.path.join(OUT, 'miner_mux4.v'), body)
print('wrote mux4/miner_mux4.v (%d lines)' % body.count('\n'))
print('  wrote mux4/cmp_256.v (%d lines)' % body.count('\n'))
print('done')
