#!/usr/bin/env python3
"""
Rewrite a generated OdoCrypt encrypt.v so that pairs of large S-boxes
share one block RAM, via 2x-clock time multiplexing.

WHY THIS IS A SCRIPT AND NOT AN EDITED FILE
-------------------------------------------
encrypt.v is generated by the upstream OdoCrypt tooling and is
regenerated every 10-day epoch (the cipher mutates). Hand-editing it
would be thrown away each epoch. This transform is mechanical, so it can
just be re-run against each new encrypt.v.

WHAT IT DOES
------------
In encrypt_4apply_sboxes, each of the 10 large tables is instantiated
exactly twice:

    encrypt_4sbox_large0 sbox2inst(clk, in[15:6],  in[31:22], out[...], out[...]);
    encrypt_4sbox_large0 sbox5inst(clk, in[47:38], in[63:54], out[...], out[...]);

Both read the same table with different addresses on every clk_h, i.e.
4 reads per table per cycle. One RAMB18 has 2 ports; clocked at 2x and
interleaved it serves 4 logical reads per clk_h -- exactly enough. So
each pair collapses into one sbox_large_mux2 and the design's block RAM
requirement halves (420 -> 210 per hash instance), letting 4 instances
fit on an XC7K325T instead of 2.

clk2x/phase are plumbed down the module chain
apply_sboxes <- full_round <- encrypt_loop <- encrypt, and the phase
generator is instantiated once at the encrypt level.

Usage:
    mux2_transform.py <in encrypt.v> <out encrypt_mux2.v>
"""
import re, sys, collections

def main(src_path, dst_path):
    src = open(src_path).read()

    # ---- 1. find the large-S-box table bodies so we can re-emit them ----
    tables = {}
    for m in re.finditer(r'module (encrypt_4sbox_large(\d+))\((.*?)\);\n(.*?)\nendmodule',
                         src, re.S):
        name, idx, _ports, body = m.group(1), int(m.group(2)), m.group(3), m.group(4)
        init = re.search(r'initial begin\n(.*?)\n    end', body, re.S)
        if not init:
            sys.exit(f"could not find initial block in {name}")
        tables[idx] = init.group(1)
    if not tables:
        sys.exit("no encrypt_4sbox_largeN modules found")
    print(f"  found {len(tables)} large S-box tables")

    # ---- 1b. MEASURE the latency of the box we are replacing ----
    #
    # odo_gen emits a 1-clk_h S-box normally:
    #
    #     always @(posedge clk) a_out <= mem[a_in];
    #
    # and a 2-clk_h one under --bram-out-reg, which infers DO_REG=1 and cuts
    # BRAM clock-to-out from 2.454ns to 0.882ns at the price of a cycle:
    #
    #     always @(posedge clk) begin
    #         a_q1  <= mem[a_in];
    #         a_out <= a_q1;
    #     end
    #
    # A muxed box whose latency does not match the one it replaces synthesises
    # cleanly, fits perfectly, and computes garbage: on 2026-09-04 that
    # combination produced permanently-X output and burned a full build before
    # the equivalence gate caught it. Measured from the source rather than read
    # off the "odo_gen flags:" header comment, because the header is a comment
    # and the pipeline is the truth.
    m = re.search(r'(\w+)\s*<=\s*mem\[a_in\]\s*;', src)
    if not m:
        sys.exit("could not find `<= mem[a_in];` -- cannot measure S-box latency")
    stock_latency = 1 if m.group(1) == "a_out" else 2
    print(f"  stock S-box latency: {stock_latency} clk_h"
          f"{'  (--bram-out-reg)' if stock_latency == 2 else ''}")

    # ---- 2. emit a muxed variant module per table ----
    muxed_mods = []
    # K register stages before the output demux, on clk2x. Two clk2x stages
    # make one clk_h, and the demux is itself one of them, so K = 2*L - 1.
    K = 2 * stock_latency - 1
    decl_q = ", ".join([f"a_q{i}" for i in range(1, K + 1)] +
                       [f"b_q{i}" for i in range(1, K + 1)])
    decl_p = ", ".join(f"phase_q{i}" for i in range(1, K + 1))

    # The read, then a plain shift register. phase is delayed alongside the
    # data by exactly the same number of stages -- that is what keeps each
    # result landing in the slot whose address produced it.
    chain = ["        a_q1     <= mem[a_addr];",
             "        b_q1     <= mem[b_addr];",
             "        phase_q1 <= phase;"]
    for i in range(2, K + 1):
        chain.append(f"        a_q{i}     <= a_q{i - 1};")
        chain.append(f"        b_q{i}     <= b_q{i - 1};")
        chain.append(f"        phase_q{i} <= phase_q{i - 1};")
    chain_s = "\n".join(chain)

    for idx in sorted(tables):
        muxed_mods.append(f"""
// Two users of large table {idx}, sharing ONE block RAM via 2x interleave.
// Drop-in for two encrypt_4sbox_large{idx} instances, matching their
// {stock_latency} clk_h latency ({K + 1} clk2x stages).
// Generated by tools/mux2_transform.py -- do not edit.
module encrypt_4sbox_large{idx}_mux2(clk2x, phase,
                                     s0_a_in, s0_b_in, s0_a_out, s0_b_out,
                                     s1_a_in, s1_b_in, s1_a_out, s1_b_out);
    input clk2x, phase;
    input [9:0] s0_a_in, s0_b_in, s1_a_in, s1_b_in;
    output reg [9:0] s0_a_out, s0_b_out, s1_a_out, s1_b_out;

    (* ram_style = "block" *)
    reg [9:0] mem[0:1023];

    wire [9:0] a_addr = phase ? s1_a_in : s0_a_in;
    wire [9:0] b_addr = phase ? s1_b_in : s0_b_in;

    reg [9:0] {decl_q};
    reg {decl_p};
    always @(posedge clk2x) begin
{chain_s}
    end
    // Each slot's output register updates on the one clk2x edge per clk_h
    // where the delayed phase selects it, so from clk_h's point of view both
    // slots hold a stable value for the whole cycle.
    always @(posedge clk2x) begin
        if (!phase_q{K}) begin s0_a_out <= a_q{K}; s0_b_out <= b_q{K}; end
        else          begin s1_a_out <= a_q{K}; s1_b_out <= b_q{K}; end
    end

    initial begin
{tables[idx]}
    end
endmodule
""")

    # ---- 3. rewrite encrypt_4apply_sboxes: pair up the large instances ----
    m = re.search(r'(module encrypt_4apply_sboxes\(clk, in, out\);\n)(.*?)(\nendmodule)',
                  src, re.S)
    if not m:
        sys.exit("encrypt_4apply_sboxes not found in expected form")
    head, body, tail = m.group(1), m.group(2), m.group(3)

    inst_re = re.compile(
        r'^\s*encrypt_4sbox_large(\d+) (\w+)\(clk, ([^,]+), ([^,]+), ([^,]+), ([^)]+)\);\s*$')
    by_table = collections.defaultdict(list)
    kept = []
    for line in body.split('\n'):
        mm = inst_re.match(line)
        if mm:
            by_table[int(mm.group(1))].append(mm.groups()[1:])
        else:
            kept.append(line)

    new_insts = []
    for idx in sorted(by_table):
        pair = by_table[idx]
        if len(pair) != 2:
            sys.exit(f"table {idx} has {len(pair)} instances, expected exactly 2 "
                     f"-- pairing assumption broken, aborting")
        (n0, a0, b0, oa0, ob0), (n1, a1, b1, oa1, ob1) = pair
        new_insts.append(
            f"    encrypt_4sbox_large{idx}_mux2 {n0}_{n1}_mux(clk2x, phase,\n"
            f"        {a0}, {b0}, {oa0}, {ob0},\n"
            f"        {a1}, {b1}, {oa1}, {ob1});")
    print(f"  paired {sum(len(v) for v in by_table.values())} large instances "
          f"into {len(new_insts)} shared-BRAM modules")

    new_apply = (head.replace("(clk, in, out)", "(clk, clk2x, phase, in, out)")
                 + "    input clk2x, phase;\n"
                 + '\n'.join(kept) + '\n'
                 + '\n'.join(new_insts) + tail)
    src = src[:m.start()] + new_apply + src[m.end():]

    # ---- 4. plumb clk2x/phase down the hierarchy ----
    src = src.replace(
        "module encrypt_4full_round(clk, roundkey, in, out);\n    input clk;",
        "module encrypt_4full_round(clk, clk2x, phase, roundkey, in, out);\n    input clk, clk2x, phase;")
    src = src.replace(
        "encrypt_4apply_sboxes sboxes(clk, mid[0], mid[1]);",
        "encrypt_4apply_sboxes sboxes(clk, clk2x, phase, mid[0], mid[1]);")

    src = src.replace(
        "module encrypt_4encrypt_loop(clk, in, read, out, write);\n    input clk;",
        "module encrypt_4encrypt_loop(clk, clk2x, phase, in, read, out, write);\n    input clk, clk2x, phase;")
    n = len(re.findall(r'encrypt_4full_round \w+\(clk,', src))
    src = re.sub(r'(encrypt_4full_round \w+\()clk,', r'\1clk, clk2x, phase,', src)
    print(f"  plumbed clk2x/phase into {n} full_round instantiations")

    # encrypt_4encrypt has a localparam between the header and "input clk",
    # so match with a regex rather than an exact string -- an exact match
    # silently does nothing and leaves clk2x/phase undeclared.
    src, n = re.subn(
        r'module encrypt_4encrypt\(clk, in, read, out, write\);\n'
        r'((?:\s*localparam[^\n]*\n)*)'
        r'    input clk;',
        lambda m: ('module encrypt_4encrypt(clk, clk2x, phase, in, read, out, write);\n'
                   + m.group(1) + '    input clk, clk2x, phase;'),
        src)
    if n != 1:
        sys.exit(f"encrypt_4encrypt header rewrite matched {n} times, expected 1")
    src = re.sub(r'(encrypt_4encrypt_loop \w+\()clk,', r'\1clk, clk2x, phase,', src)

    # Every module that now references clk2x/phase must also declare them.
    for mod in ("encrypt_4apply_sboxes", "encrypt_4full_round",
                "encrypt_4encrypt_loop", "encrypt_4encrypt"):
        body = re.search(r'module ' + mod + r'\(.*?\nendmodule', src, re.S)
        if not body:
            sys.exit(f"{mod} missing after transform")
        b = body.group(0)
        if "clk2x" in b and "input clk, clk2x, phase;" not in b and "input clk2x, phase;" not in b:
            sys.exit(f"{mod} uses clk2x/phase but does not declare them -- transform bug")
    print("  verified: all rewritten modules declare clk2x/phase")

    # ---- 5. append the muxed table modules ----
    src += "\n" + "\n".join(muxed_mods)

    open(dst_path, "w").write(src)
    print(f"  wrote {dst_path}")

if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
