// GENERATED by tools/make_mux4_variants.py -- do not edit by hand.
//
// Derived from ../odocrypt/miner_pipelined.v + odocrypt/miner.v for the 4-instance shared-BRAM experiment.
// The shipping file is untouched; see mux4/miner_mux4.v for what the
// experiment is, what it costs, and why it is an experiment.
//
//
// The clk2x/phase-carrying variants for the 4-instance shared-BRAM
// experiment. Both modules are the shipping ones with two extra input
// ports threaded through to encrypt_4encrypt -- nothing else differs,
// which is why this is generated rather than copied.
//
// THROUGHPUT guard, carried over from the hand-written file it
// replaced. Without it the `THROUGHPUT references below depend on
// some other file having defined it first -- a silent dependency on
// compile order. Found by diffing this output against that file.
`ifndef THROUGHPUT
`define THROUGHPUT 4
`endif

module odo_keccak_mux4(clk, clk2x, phase, in, read, target, out, write);
	input clk2x;
	input phase;
	input clk;
	input [639:0] in;
	input read;
	input [255:0] target;
	output out; //ticket2moon
	output write;

	wire [639:0] midstate;
	wire midread;
	wire [255:0] pow_hash;
	wire has_hash;

	encrypt_4encrypt crypt(clk, clk2x, phase, in, read, midstate, midread);
	keccak_hasher #(640, `THROUGHPUT) hash(clk, midstate, midread, pow_hash, has_hash);
	cmp_256 compare(clk, pow_hash, has_hash, target, out, write);
endmodule

module miner_pipelined_mux4(clk, clk2x, phase, header, target, nonce, found);
    parameter INONCE = 0; // NONCE_BASE for this instance, same convention as
                           // miner.v's NONCE_BASE

    input clk;
    input clk2x;
    input phase;
    input [607:0] header;
    input [255:0] target;
    output reg [31:0] nonce;
    // 1-cycle strobe, asserted on the same edge `nonce` latches a qualifying
    // nonce. Lets the wrapper push EVERY find exactly once into a FIFO
    // instead of inferring finds from a change in `nonce` (which loses a
    // find whenever a new winner equals the value already latched, or when
    // the FIFO is full).
    output reg found;

    reg [31:0] nonce_in;
    reg [31:0] nonce_out;
    initial nonce_in = INONCE;
    initial nonce_out = INONCE;

    reg [6:0] counter;
    reg advance;
    initial counter = `THROUGHPUT-1;
    initial advance = 0;
    initial found = 0;

    wire res;
    wire has_res;

    odo_keccak_mux4 worker(clk, clk2x, phase, {nonce_in, header}, advance,
                           target, res, has_res);

    always @(posedge clk)
    begin
        if (counter == `THROUGHPUT-1)
        begin
            counter <= 0;
            advance <= 1;
        end
        else
        begin
            counter <= counter + 1;
            advance <= 0;
        end
        if (advance)
            nonce_in <= nonce_in + 1;
        found <= 1'b0;            // default: one-cycle pulse
        if (has_res)
        begin
            // `nonce` DELIBERATELY shares nonce_out's enable. It used to sit
            // inside `if (res)`, giving it a clock enable of (has_res & res) --
            // a LUT2 -- while nonce_out's was has_res alone, a strictly shorter
            // path. If that combined term missed the setup window at an edge,
            // nonce_out incremented anyway and `nonce` loaded one cycle later,
            // capturing the ALREADY-INCREMENTED value: a nonce reported exactly
            // one too high.
            //
            // Measured on hardware 2026-09-07 at 225MHz: ~36% of finds, both
            // instances, always +1 and never +2, non-accumulating. The sign is
            // what localises it -- a slip anywhere on the cipher-input side
            // would report a nonce too LOW, and a gained or lost strobe pulse
            // would desync nonce_out cumulatively and show -2, -3, -4. Those
            // buckets measured exactly zero.
            //
            // Loading every result rather than only qualifying ones is
            // equivalent for the consumer: found_path samples `nonce`
            // combinationally in the cycle `found` is high, and it holds that
            // result's nonce then. `res` becomes plain data on `found` instead
            // of half an enable, so the two registers cannot disagree about
            // which edge they belong to.
            nonce     <= nonce_out;
            found     <= res;        // one-cycle strobe; default above clears it
            nonce_out <= nonce_out + 1;
        end
    end
endmodule
