// GENERATED by tools/make_mux4_variants.py -- do not edit by hand.
//
// Derived from ../odocrypt_gpio_wrapper.v for the 4-instance shared-BRAM experiment.
// The shipping file is untouched; see mux4/miner_mux4.v for what the
// experiment is, what it costs, and why it is an experiment.
//
//////////////////////////////////////////////////////////////////////////////////
/*
 *  AtomMiner AM01 -- QMTECH Kintex-7 + Raspberry Pi CM4 variant, design proposal
 *
 *  Copyright 2015-2022 AtomMiner <atom@atomminer.com>
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 * This program is free software; you can redistribute it and/or modify it
 * under the terms of the GNU General Public License as published by the Free
 * Software Foundation; either version 3 of the License, or (at your option)
 * any later version. If not, see <http://www.gnu.org/licenses/>.
 *
 */
//////////////////////////////////////////////////////////////////////////////////
//
// odocrypt_gpio_wrapper
//
// Replacement for exmaples/odocrypt/fpga/src/hdl/usb3_interface.v +
// usb3_sm_v3.v on the QMTECH XC7K325T + Raspberry Pi CM4 variant (see
// ../README.md). A Raspberry Pi CM4 plugged into the QMTECH board's CM4
// socket drives header/target words and reads the golden nonce over 24
// general-purpose GPIO lines using a simple 4-phase parallel bus, instead
// of the FX3's DQ-bus/USB link or the Zynq variant's on-chip AXI4-Lite.
// odo_block_data is reused unmodified from hdl/odocrypt/ (a copy of
// exmaples/odocrypt/fpga/src/hdl/ kept in sync with the current OdoCrypt
// epoch -- see hdl/odocrypt/NOTICE).
//
// v2.0 no longer uses that tree's miner_top/host_break_sm. The hash cores
// are hdl/odocrypt/miner_pipelined.v, adopted from odo-miner-cyclonev: they
// free-run rather than halting on every find and being re-armed, which is
// what the AtomMiner lineage did and what four separate nonce-alignment
// bugs traced back to. See the VERSION 0x0200 note below.
//
// STATUS: reference skeleton for a hardware proposal, not verified/timed
// silicon-ready RTL. See "What's still needed before this is real
// hardware" in ../README.md -- in particular gpio_wr_n/gpio_rd_n/
// gpio_addr/gpio_data are asynchronous inputs from the CM4 (no shared
// clock), synchronized here with plain multi-flop synchronizers that
// still need ASYNC_REG + timing-exception signoff before tape-out.
//
// Register map (see ../README.md): 16-bit-per-beat, ADDR-selected.
//
`timescale 1ns / 1ps

module odocrypt_gpio_wrapper_mux4 #(
    // Number of parallel hash-core instances. BRAM-bound on this chip:
    // one instance = 420 RAMB18 of the XC7K325T's 890 (measured), so 2
    // fills the budget at 94% and 3 does not fit. Set to 1 to get the
    // original single-core behaviour back. See ../README.md
    // "Expected hashrate" for the derivation.
    parameter integer NUM_MINERS = 4,

    // Cycles of found-reporting suppression after each job commit.
    // SIMULATION OVERRIDE ONLY -- see the SETTLE_CYCLES comment further down
    // for why it is 4096 and what goes wrong when it is too small. The
    // testbench drives it to 0 as a negative control.
    parameter integer SETTLE_CYCLES_P = 4096,

    // OdoCrypt epoch seed that hdl/odocrypt/encrypt.v was generated for,
    // read back by the host at SEED_LO/SEED_HI as bitstream_epoch.
    //
    // The default is the real value rather than 0 so it is correct without
    // either build flow having to pass a generic. It MUST match the seed
    // stamped in encrypt.v's header -- tools/check-epoch.sh enforces that and
    // flags staleness against the current date. Update both together.
    parameter [31:0] ODO_SEED = 32'd1788480000
) (
    // ---------------------------------------------------------------
    // Bus clock domain -- the board's onboard 50MHz crystal
    // (sys_clk_50m in the .xdc), or an MMCM-derived clock from it.
    // ---------------------------------------------------------------
    input  wire        bus_clk,
    input  wire        bus_rst_n,

    // ---------------------------------------------------------------
    // GPIO parallel bus to the CM4 socket. Asynchronous to bus_clk --
    // driven either by bit-banged GPIO or the BCM2711 SMI peripheral.
    // ---------------------------------------------------------------
    inout  wire [15:0] gpio_data,
    // 5 bits. GPIO16-19 were the original four; GPIO24 (FPGA ball B14) is
    // added as addr[4]. It was already routed to the FPGA -- the manual's
    // section 2.2.9 table wires GPIO0-27 to fabric -- but unused by this
    // design, so widening cost a constraint rather than a wire. 4 bits gave
    // 16 slots and all 16 were allocated once the XADC and fan registers
    // landed, leaving nowhere for the display.
    input  wire [4:0]  gpio_addr,
    input  wire        gpio_wr_n,   // active low
    input  wire        gpio_rd_n,   // active low
    output reg          gpio_ready,
    output wire        gpio_irq,    // level, asserted while a nonce is pending

    // ---------------------------------------------------------------
    // Hash-core clock domain. clk_h is whatever feeds the miner cores today
    // (an MMCM output derived from the 50MHz crystal, same role
    // artix200_v3_clocking plays on the stock AM01).
    // ---------------------------------------------------------------
    input  wire        clk_h,
    // 2 x clk_h from the SAME MMCM, phase-aligned. Only the muxed
    // S-boxes use it; every other path stays on clk_h.
    input  wire        clk_2x,

    // ---------------------------------------------------------------
    // Fan, on spare BANK12 I/O at JP5. PWM out, tach in. Driven from
    // fabric so cooling works with no software running.
    // ---------------------------------------------------------------
    output wire        fan_pwm,
    input  wire        fan_tach_in,

    // ---------------------------------------------------------------
    // ILI9341 panel + XPT2046 touch on JP5, sharing one SPI bus.
    // ---------------------------------------------------------------
    output wire        lcd_sclk,
    output wire        lcd_mosi,
    input  wire        lcd_miso,
    output wire        lcd_cs_n,
    output wire        lcd_dc,
    output wire        lcd_rst_n,
    output wire        lcd_bl,
    output wire        touch_cs_n,
    input  wire        touch_irq,

    // ---------------------------------------------------------------
    // CYD front panel: a serial link on its OWN JP5 pins.
    //
    // These do NOT share the display's pins. JP5 carries 21 BANK12 signal
    // pairs and this design uses only 5-13 (display/touch) and 45-46 (fan),
    // so pins 14-44 were sitting unconstrained -- thirty of them. Taking four
    // means the ILI9341 and a CYD can be wired at the same time, one
    // bitstream serves both, and the display path needs no mux, no
    // build-time parameter, and no modification at all.
    //
    // An earlier revision of this reused lcd_sclk/lcd_miso/lcd_cs_n/lcd_dc.
    // It worked, but it made the two panels mutually exclusive for no reason
    // and left every one of those port names describing hardware it was no
    // longer driving -- which is how the next person reading the XDC ends up
    // scoping the wrong pin.
    // ---------------------------------------------------------------
    output wire        cyd_uart_tx,   // JP5 15 -> CYD RX
    input  wire        cyd_uart_rx,   // JP5 16 <- CYD TX
    output wire        cyd_esp_en,    // JP5 17 -> ESP32 EN (reset)
    output wire        cyd_esp_io0    // JP5 18 -> ESP32 IO0 (boot select)
);

    // -----------------------------------------------------------------
    // Register map
    // -----------------------------------------------------------------
    localparam [4:0] ADDR_VERSION     = 5'h0;
    localparam [4:0] ADDR_CTRL        = 5'h1;
    localparam [4:0] ADDR_STATUS      = 5'h2;
    localparam [4:0] ADDR_NONCE_LO    = 5'h3;
    localparam [4:0] ADDR_NONCE_HI    = 5'h4;
    localparam [4:0] ADDR_HEADER_LO   = 5'h5;
    localparam [4:0] ADDR_HEADER_HI   = 5'h6;
    localparam [4:0] ADDR_TARGET_LO   = 5'h7;
    localparam [4:0] ADDR_TARGET_HI   = 5'h8;
    // Read-only: the OdoCrypt epoch seed encrypt.v was generated for. The
    // daemon reads this back as bitstream_epoch and compares it against the
    // pool's job epoch; without it a stale bitstream mines rejects silently.
    localparam [4:0] ADDR_SEED_LO     = 5'h9;
    localparam [4:0] ADDR_SEED_HI     = 5'hA;
    // Raw XADC on-die temperature code, 16 bits as read from DRP 0x00 (only
    // the top 12 bits are significant). Converted host-side rather than here:
    //     degC = (code >> 4) * 503.975 / 4096 - 273.15
    // A raw value keeps the RTL to a latch and avoids fixed-point in fabric.
    // Reads 0 until the first conversion completes, a few us after reset.
    localparam [4:0] ADDR_TEMP        = 5'hB;
    // Supply rails, same XADC, same DRP, different channels. Default mode
    // already samples these alongside temperature, so they cost one more
    // latch each. VCCINT matters most: this design draws ~12A at 1.0V through
    // the MP8712, and a sagging core rail produces wrong hash results while
    // everything still looks healthy -- silent rejects, not a crash.
    //     volts = (code >> 4) * 3.0 / 4096
    localparam [4:0] ADDR_VCCINT      = 5'hC;
    localparam [4:0] ADDR_VCCAUX      = 5'hD;
    localparam [4:0] ADDR_VCCBRAM     = 5'hE;
    // Fan. Read : [7:0] current duty (0-255), [15:8] tach pulses/sec.
    //      Write: [7:0] minimum duty floor; 0 = fully automatic.
    // Control is closed-loop in fabric off the XADC die temperature, so the
    // fan is correct from power-on -- before Linux boots, and regardless of
    // whether the Pi or the miner is alive. This design free-runs at full
    // power the moment it configures from flash, so cooling must not depend
    // on software having started.
    localparam [4:0] ADDR_FAN         = 5'hF;

    // ---- ILI9341 display, in the space the 5th address bit opened up ----
    // The panel has its own GRAM, so the FPGA never holds a framebuffer --
    // it is a transport: the host writes command/data bytes and they go out
    // over SPI. That is why this needs no BRAM, which matters at 94% RAMB18.
    //
    // LCD_DATA is deliberately its own slot: pixel writes are the only
    // high-traffic path here, and keeping them on a fixed address means the
    // host can hammer one register without re-addressing.
    localparam [4:0] ADDR_LCD_CMD     = 5'h10;  // write: command byte, DC=0
    localparam [4:0] ADDR_LCD_DATA    = 5'h11;  // write: data/pixel, DC=1
    localparam [4:0] ADDR_LCD_STAT    = 5'h12;  // read: busy/fifo state
    localparam [4:0] ADDR_LCD_CTRL    = 5'h13;  // write: [0] RST_N [1] backlight
    localparam [4:0] ADDR_TOUCH_X     = 5'h14;  // read: XPT2046 X
    localparam [4:0] ADDR_TOUCH_Y     = 5'h15;  // read: XPT2046 Y
    localparam [4:0] ADDR_TOUCH_STAT  = 5'h16;  // read: [0] pressed
    // 8-bit data write, DC=1. The ILI9341's single-byte parameters
    // (COLMOD, MADCTL) cannot be sent through the 16-bit LCD_DATA slot
    // without emitting a second, surplus byte after them.
    localparam [4:0] ADDR_LCD_DATA8   = 5'h17;  // write: 8-bit data, DC=1

    // v2.0. read: [15:8] saturating lost-find count, [3:0] found-FIFO depth.
    // Exists so a dropped find is VISIBLE. v1.x had a single nonce latch that
    // a second find would overwrite silently, and the only symptom was a
    // share that never arrived -- indistinguishable from bad luck.
    localparam [4:0] ADDR_FIFO_STAT   = 5'h18;  // read: {lost[7:0], 4'h0, depth[3:0]}

    // CYD front panel, on its own JP5 pins (15-18). Always present, and
    // harmless with no CYD attached: an unread RX FIFO simply stays empty.
    // See hdl/uart_bridge.v and docs/PLAN-cyd-display.md.
    localparam [4:0] ADDR_UART_DATA   = 5'h19;  // w: push TX byte  r: pop RX byte
    localparam [4:0] ADDR_UART_STAT   = 5'h1A;  // r: {rx_err[3:0], tx_cnt[4:0],
                                                //     rx_cnt[4:0], tx_full,
                                                //     rx_empty}
    localparam [4:0] ADDR_ESP_CTRL    = 5'h1B;  // w: [0] EN  [1] IO0

    // v1.1 adds SEED_LO/SEED_HI. The daemon treats a VERSION below this as
    // "seed unreadable" rather than misreading 0 as a real epoch.
    // v1.2 adds TEMP, the XADC supply rails, and autonomous fan control.
    // v1.3 widens gpio_addr to 5 bits and adds the ILI9341/XPT2046 block.
    // v1.4 adds LCD_DATA8 (8-bit DC=1, for single-byte panel parameters)
    // and makes the XPT2046 real: it was declared in v1.3 but stubbed --
    // touch_cs_n was tied high and touch_x/touch_y were never written.
    // A v1.2-or-older host driving only 4 address lines still works: the
    // fifth line idles low, so it addresses 0x00-0x0F exactly as before.
    // 0x0108: miner.v nonce_out now counts EVERY result. Gating the counter on
    // nonce_out_go desynchronised it from the result stream, which is what
    // actually produced the wrong nonces. THIS is the fix that matters.
    // 0x0107: settle window widened 205 -> 4096 cycles, matching the value the
    // Cyclone V build uses for this same core. See the SETTLE_CYCLES note.
    // 0x0106: target_word_cnt_h narrowed to 3 bits. The version bump is
    // LOAD-BEARING, not cosmetic -- am01_bus_submit_work() uses it to decide
    // whether it must send the target words twice to work around the
    // every-other-dispatch arming bug in 0x0105 and earlier.
    //
    // 0x0200 -- MAJOR bump, because the core changed and the interface with it.
    //
    // The AtomMiner core (miner.v) is gone, replaced by the free-running
    // miner_pipelined. Four separate RTL fixes (0x0106 arming, 0x0107 settle
    // width, 0x0108 nonce_out gating, 0x0109 golden_nonce latch timing) were
    // all symptoms of one root cause: miner.v resets nonce_in/nonce_out to
    // NONCE_BASE on every halt, and that core halts on EVERY find, so every
    // single find restarted the warm-up from zero. Measured on hardware
    // 2026-08-31 with a header-cycling am01_smoke: 16/16 wrong nonces the
    // moment each dispatch explored fresh nonce territory instead of
    // deterministically replaying an already-good sequence.
    //
    // What changed at the interface:
    //   * the 8th target word COMMITS a job instead of ARMING the core; the
    //     cores never stop, so there is nothing to arm
    //   * STATUS.hash_active now means "committed job, settle window closed",
    //     not "armed"
    //   * OP_HOST_BREAK (CTRL bit 1) is accepted and ignored
    //   * new ADDR_FIFO_STAT (0x18): found-FIFO depth and lost-find count
    // Header/target word order, NONCE_LO/HI, and the read-HI-clears-valid
    // convention are all unchanged, so a v1.x host still dispatches and
    // drains correctly -- it just cannot see the new FIFO telemetry.
    //
    // 0x0201: the nonce consume/ack moved to the END of the read transaction.
    // At 0x0200 it fired on the first cycle of S_READ, which -- now that it
    // also acks the found-FIFO -- let clk_h swap the latch mid-read and hand
    // the host one nonce's low half with another's high half. See the
    // ADDR_NONCE_HI note in S_READ. found_path also flushes the FIFO on
    // commit. No interface change; 0x0200 bitstreams are simply wrong.
    //
    // 0x0202: adds the CYD serial link on JP5 15-18 -- UART_DATA (0x19),
    // UART_STAT (0x1A), ESP_CTRL (0x1B). Purely additive: nothing existing
    // moved, and a host that never touches those three registers cannot tell
    // this apart from 0x0201. The version bump exists so am01-uartd can
    // REFUSE to run against a bitstream with no UART in it, rather than
    // reading back zeros from unmapped addresses and reporting a dead panel.
    // 0x0203: UART_STAT's layout changed, and found_path gained a reset.
    //
    // NOT backward compatible for UART_STAT readers -- the fields moved. That
    // is acceptable only because 0x0202 never reached a board: the sole
    // consumer is am01-uartd, which gates on VERSION and is updated with it.
    //
    // The found_path change is the important one. Its `busy` flag was
    // clearable only by a host ack and the module had no reset, so a host
    // killed between a nonce handover and its ack stalled the found path
    // permanently -- surviving restarts, recoverable only by reconfiguring
    // the FPGA. It cost an hour of mining on 2026-09-01. OP_SOFT_RESET now
    // reaches it and the daemon issues one at startup.
    localparam [15:0] VERSION = 16'h0203;

    // Request opcodes carried across the bus_clk -> clk_h handshake.
    localparam [1:0] OP_HEADER_WORD = 2'b00;
    localparam [1:0] OP_TARGET_WORD = 2'b01;
    localparam [1:0] OP_HOST_BREAK  = 2'b10;
    localparam [1:0] OP_SOFT_RESET  = 2'b11;

    // =====================================================================
    // Synchronize the async CM4-driven bus into bus_clk. ADDR/DATA are
    // sampled only once WR_N/RD_N has been seen low for two consecutive
    // bus_clk cycles, so they're required to be stable before the strobe
    // asserts -- standard practice for a source-synchronous-ish bus with
    // no shared clock.
    // =====================================================================
    // ASYNC_REG on the first flop of each chain: tells P&R to place it
    // close to whatever feeds it and prioritize it for MTBF, since it's
    // the one actually catching an asynchronous input mid-transition.
    // Paired with the set_clock_groups -asynchronous in the .xdc between
    // sys_clk_50m and clk_h -- that tells STA these two clocks aren't
    // meant to be timed against each other; this tells P&R the flops
    // that assumption depends on need real metastability handling.
    // wr_sync/rd_sync are stored ACTIVE-HIGH (inverted from the raw
    // active-low gpio_wr_n/gpio_rd_n) purely so their idle/reset state is
    // all-zero instead of all-one. That is not cosmetic: a reset-to-1
    // register synthesizes to FDSE ("set" primitive) instead of FDRE
    // ("reset" primitive), and FDRE/FDSE turn out to be JUST as
    // half-slice-incompatible as the sync/async split above -- confirmed
    // by hitting a second real 'control-set contention' FASM error, on
    // this exact register, after already eliminating FDCE/FDPE. Same
    // fix category, one bit of polarity instead of a sensitivity list.
    // Functionally identical either way -- see wr_active/rd_active and
    // the S_WRITE/S_READ release checks below, which un-invert as needed.
    (* ASYNC_REG = "TRUE" *) reg [2:0] wr_sync, rd_sync;
    (* ASYNC_REG = "TRUE" *) reg [4:0] addr_sync0;
    reg [4:0]  addr_sync1;
    (* ASYNC_REG = "TRUE" *) reg [15:0] data_in_sync0;
    reg [15:0] data_in_sync1;

    // Synchronous reset deliberately, not async: bus_rst_n is already
    // deasserted synchronously (see am01_qmtech_top.v's rst_stretch
    // counter), so nothing here needs true async behaviour. Kept sync
    // for a real, measured reason -- see openxc7/README.md "Why every
    // reset in this file is synchronous": Xilinx 7-series async-set/
    // reset FFs (FDCE/FDPE) route through the same half-slice control
    // network as the sync ones (FDRE/FDSE), and nextpnr-xilinx's placer
    // does not reliably keep the two families apart -- confirmed via a
    // real 'control-set contention' FASM error on 2/2 random seeds
    // before this fix. Vivado handles the mix fine; this is an openXC7
    // portability fix, not a correctness bug this file ever had.
    always @(posedge bus_clk) begin
        if (!bus_rst_n) begin
            wr_sync <= 3'b000;
            rd_sync <= 3'b000;
        end else begin
            wr_sync <= {wr_sync[1:0], ~gpio_wr_n};
            rd_sync <= {rd_sync[1:0], ~gpio_rd_n};
        end
    end

    always @(posedge bus_clk) begin
        addr_sync0 <= gpio_addr;
        addr_sync1 <= addr_sync0;
        data_in_sync0 <= gpio_data;
        data_in_sync1 <= data_in_sync0;
    end

    wire wr_active = wr_sync[2] & wr_sync[1]; // debounced write request
    wire rd_active = rd_sync[2] & rd_sync[1]; // debounced read request

    // =====================================================================
    // bus_clk -> clk_h request/ack handshake (same two-phase toggle
    // synchronizer pattern as hardware/zynq/hdl/odocrypt_axi_wrapper.v).
    // req_toggle_bus only flips once the previous request has been
    // ack'd, enforced below by holding the bus state machine (and thus
    // GPIO_READY) until ack_pulse_bus arrives, so req_op/req_data are
    // guaranteed stable for the whole round trip.
    // =====================================================================
    reg        req_toggle_bus;
    reg [1:0]  req_op_bus;
    reg [31:0] req_data_bus;

    (* ASYNC_REG = "TRUE" *) reg req_sync1_h;
    reg req_sync2_h, req_sync3_h;
    reg ack_toggle_h;
    (* ASYNC_REG = "TRUE" *) reg ack_sync1_bus;
    reg ack_sync2_bus, ack_sync3_bus;

    wire req_pulse_h   = req_sync2_h ^ req_sync3_h;
    wire ack_pulse_bus = ack_sync2_bus ^ ack_sync3_bus;

    always @(posedge clk_h) begin
        req_sync1_h <= req_toggle_bus;
        req_sync2_h <= req_sync1_h;
        req_sync3_h <= req_sync2_h;
        if (req_pulse_h)
            ack_toggle_h <= ~ack_toggle_h;
    end

    always @(posedge bus_clk) begin
        ack_sync1_bus <= ack_toggle_h;
        ack_sync2_bus <= ack_sync1_bus;
        ack_sync3_bus <= ack_sync2_bus;
    end

    // =====================================================================
    // XADC on-die temperature.
    //
    // The Kintex-7 has a built-in temperature sensor; this is the die
    // temperature, not a heatsink probe, which is what actually matters for
    // a design that free-runs at full power the moment it configures. There
    // is nowhere on this board to attach an external sensor anyway: all 28
    // CM4 GPIOs go to FPGA fabric pins and JP5 is FPGA I/O, so the daemon's
    // DS18B20 support (inherited from the Cyclone V variant) cannot be used.
    //
    // Default mode (CFG1[15:12]=0000) free-runs a sequence including the
    // temperature channel with no sequencer setup, so this only has to poll
    // DRP address 0x00 and latch the result. ADCCLK = DCLK/8 = 6.25MHz from
    // the 50MHz bus_clk, inside the 1-26MHz the ADC requires.
    //
    // VP/VN are tied off: the internal sensor does not use the external
    // analog inputs, and the schematic grounds DXP_0/DXN_0.
    // =====================================================================
    wire [15:0] xadc_do;
    wire        xadc_drdy;
    reg         xadc_den;
    reg  [6:0]  xadc_daddr;
    reg  [1:0]  xadc_chan;      // which of the four we are currently reading
    reg  [15:0] xadc_temp_bus;
    reg  [15:0] xadc_vccint_bus;
    reg  [15:0] xadc_vccaux_bus;
    reg  [15:0] xadc_vccbram_bus;
    reg  [7:0]  xadc_wait;

    // DRP addresses, in the order xadc_chan cycles through them.
    function [6:0] chan_addr(input [1:0] c);
        case (c)
            2'd0: chan_addr = 7'h00;  // temperature
            2'd1: chan_addr = 7'h01;  // VCCINT
            2'd2: chan_addr = 7'h02;  // VCCAUX
            default: chan_addr = 7'h06;  // VCCBRAM
        endcase
    endfunction

    always @(posedge bus_clk or negedge bus_rst_n) begin
        if (!bus_rst_n) begin
            xadc_den         <= 1'b0;
            xadc_daddr       <= 7'h00;
            xadc_chan        <= 2'd0;
            xadc_temp_bus    <= 16'h0000;
            xadc_vccint_bus  <= 16'h0000;
            xadc_vccaux_bus  <= 16'h0000;
            xadc_vccbram_bus <= 16'h0000;
            xadc_wait        <= 8'd0;
        end else begin
            xadc_den <= 1'b0;                 // single-cycle strobe

            if (xadc_drdy) begin
                case (xadc_chan)
                    2'd0: xadc_temp_bus    <= xadc_do;
                    2'd1: xadc_vccint_bus  <= xadc_do;
                    2'd2: xadc_vccaux_bus  <= xadc_do;
                    2'd3: xadc_vccbram_bus <= xadc_do;
                endcase
                xadc_chan <= xadc_chan + 2'd1;   // wraps at 4
            end

            // One channel roughly every 256 bus_clk cycles (~5us), so all
            // four refresh in ~20us -- far faster than either the sensor
            // changes or the host polls, and light enough on the DRP port.
            if (xadc_wait == 8'd0) begin
                xadc_daddr <= chan_addr(xadc_chan);
                xadc_den   <= 1'b1;
                xadc_wait  <= 8'hFF;
            end else begin
                xadc_wait <= xadc_wait - 8'd1;
            end
        end
    end

    // NO_XADC builds the design without the on-die monitor.
    //
    // Not a preference -- the open-source flow CANNOT place an XADC on this
    // part. prjxray's kintex7 database contains zero XADC/MONITOR tiles, so
    // nextpnr-xilinx has no bel to bind to and place-and-route dies with
    //   ERROR: Unable to place cell '...xadc_inst', no Bels remaining of
    //          type 'XADC'
    // nextpnr's only mentions of XADC are an invertible-pin entry and an
    // error message; there is no packer support. Closing that gap means
    // fuzzing the XADC configuration into prjxray, which is real work.
    //
    // Leaving the reads tied to zero is already a defined state rather than a
    // hack: the fan controller below treats a raw code of 0 as "the XADC has
    // not produced a reading" and falls back to full-speed cooling, which is
    // exactly the correct behaviour for a bitstream that has no monitor.
    // Vivado builds are unaffected -- do not pass the define there.
`ifdef NO_XADC
    assign xadc_do   = 16'h0000;
    assign xadc_drdy = 1'b0;
`else
    XADC #(
        .INIT_40(16'h0000),   // CFG0: no averaging, unipolar, temperature
        .INIT_41(16'h0F0F),   // CFG1: default mode, all alarms disabled
        .INIT_42(16'h0800),   // CFG2: DCLK divider = 8 -> ADCCLK 6.25MHz
        .SIM_MONITOR_FILE("design.txt")
    ) xadc_inst (
        .DADDR  (xadc_daddr),
        .DCLK   (bus_clk),
        .DEN    (xadc_den),
        .DI     (16'h0000),
        .DWE    (1'b0),
        .DO     (xadc_do),
        .DRDY   (xadc_drdy),
        .RESET  (~bus_rst_n),
        .VP     (1'b0),
        .VN     (1'b0),
        .VAUXP  (16'h0000),
        .VAUXN  (16'h0000),
        .CONVST (1'b0),
        .CONVSTCLK (1'b0),
        .JTAGBUSY  (),
        .JTAGLOCKED(),
        .JTAGMODIFIED(),
        .OT     (),
        .ALM    (),
        .MUXADDR(),
        .CHANNEL(),
        .EOC    (),
        .EOS    (),
        .BUSY   ()
    );
`endif

    // =====================================================================
    // ILI9341 display + XPT2046 touch, sharing one SPI bus.
    //
    // The FPGA is a transport here, not a graphics engine: the panel has its
    // own GRAM, so nothing is stored on this side. The host writes a command
    // byte to LCD_CMD (DC low) or a 16-bit pixel to LCD_DATA (DC high) and
    // this shifts it out. No framebuffer means no BRAM, which is the only
    // reason it fits in a design already at 94% RAMB18.
    //
    // SCLK is bus_clk/8 = 6.25MHz. Conservative on purpose -- none of this
    // has been near real silicon, and a slow bus is far easier to debug than
    // a marginal one.
    // =====================================================================
    // The shifter is 24 bits wide because an XPT2046 exchange is one:
    // an 8-bit control byte followed by 16 clocks during which the result
    // comes back. LCD traffic left-aligns into the same register.
    reg  [23:0] spi_shift;
    reg  [23:0] spi_rx;      // MISO sampled on the rising edge (SPI mode 0)
    reg  [5:0]  spi_bits;
    reg         spi_cs_touch_n;
    reg         spi_rx_en;   // only the touch path cares about MISO
    reg         spi_is_touch; // which client owns the transfer in flight
    reg  [4:0]  spi_div_max;  // half-period, in bus_clk cycles, minus one

    // bus_clk is 50MHz (sys_clk_50m straight through -- see
    // am01_qmtech_top.v). Getting that wrong is what produced two defects
    // here: a touch clock 3x over the XPT2046's limit, and a poll interval
    // comment that was out by 2x.
    //
    // Panel: half-period 4 cycles -> 6.25MHz, comfortably inside the
    // ILI9341's rating.
    // Touch: the XPT2046's DCLK maximum is 2.0MHz, so half-period 16 cycles
    // -> 1.5625MHz.
    localparam [4:0] SPI_DIV_LCD   = 5'd3;
    localparam [4:0] SPI_DIV_TOUCH = 5'd15;
    reg  [4:0]  spi_div;
    reg         spi_busy;
    reg         spi_dc;
    reg         spi_cs_lcd_n;
    reg         spi_sclk;
    reg         spi_mosi;
    reg         lcd_rst_n_r;
    reg         lcd_bl_r;
    reg  [11:0] touch_x, touch_y;
    reg         touch_pressed;

    // ---- XPT2046 touch sequencer ------------------------------------
    // Shares the SPI shifter with the panel. The LCD has priority: a touch
    // exchange only starts when the shifter is idle AND no panel write is
    // pending, so pixel traffic is never held up by touch polling. A whole
    // exchange is 24 SPI bits at bus_clk/8, roughly 4us, so a panel write
    // that does arrive mid-exchange waits a negligible time -- and the host
    // already polls LCD_STAT before writing.
    wire lcd_pending = (lcd_req_toggle != lcd_req_seen);

    localparam [1:0] T_IDLE   = 2'd0,
                     T_READ_X = 2'd1,
                     T_READ_Y = 2'd2,
                     T_SETTLE = 2'd3;
    // Control bytes: S=1, 12-bit, differential, power-down between reads.
    //   X position -> A2:A0 = 101 -> 8'hD0
    //   Y position -> A2:A0 = 001 -> 8'h90
    localparam [7:0] XPT_CMD_X = 8'hD0;
    localparam [7:0] XPT_CMD_Y = 8'h90;
    // touch_irq is an asynchronous open-drain pad. It was sampled directly,
    // which was survivable while it only fed a status register; it now gates
    // an FSM, so it gets a two-flop synchroniser.
    reg  [1:0]  touch_irq_sync;
    reg  [1:0]  touch_state;
    reg  [19:0] touch_tick;     // rate limiter between poll rounds
    reg         touch_start;
    reg  [7:0]  touch_ctrl;

    // Driven by the bus FSM on a write to LCD_CMD / LCD_DATA / LCD_CTRL.
    //
    // A TOGGLE, not a level. lcd_start used to be held high until the bus FSM
    // returned to S_IDLE, which does not happen until the CM4 releases WR_N --
    // a libgpiod ioctl away, microseconds. A transfer takes 1.28-2.56us, so
    // the shifter finished, saw the request still asserted, and sent the same
    // byte again: every write went out 2-10 times. Exactly the surplus-byte
    // fault LCD_DATA8 was added to avoid, inherited by LCD_DATA8 itself.
    //
    // The toggle is edge-like but survives any clock-domain skew, and it keeps
    // a single driver for each register -- the bus FSM owns lcd_req_toggle,
    // the SPI engine owns lcd_req_seen. Clearing a shared flag from both would
    // be a multiple-driver conflict, which this design has hit before.
    // DEPTH ONE. A toggle carries at most one outstanding request: two writes
    // issued before the engine takes the first flip it twice, which cancels
    // and loses BOTH silently. The host must not write while the shifter is
    // busy -- am01_panel.c polls LCD_STAT before every write, which
    // guarantees it, and LCD_STAT exists for exactly this.
    //
    // Do not remove that polling as an optimisation. The toggle fix stops
    // writes being REPEATED, it does not make the interface queue. Dropping
    // the poll would trade a duplicate-byte fault for a lost-byte one.
    reg         lcd_req_toggle;
    reg         lcd_req_seen;
    reg  [15:0] lcd_start_data;
    reg         lcd_start_dc;
    reg         lcd_start_16;
    reg         lcd_ctrl_wr;
    reg  [15:0] lcd_ctrl_data;

    // The display pins, untouched. The CYD link is on its own pins, so there
    // is nothing to mux and these are exactly what they always were.
    assign lcd_sclk   = spi_sclk;
    assign lcd_mosi   = spi_mosi;
    assign lcd_cs_n   = spi_cs_lcd_n;
    assign lcd_dc     = spi_dc;
    assign lcd_rst_n  = lcd_rst_n_r;
    assign lcd_bl     = lcd_bl_r;
    assign touch_cs_n = spi_cs_touch_n;

    // ---- CYD serial link -------------------------------------------------
    // On JP5 15-18, which nothing else uses. The display block above is
    // therefore untouched, and a board with an ILI9341 and no CYD sees no
    // behavioural difference at all.
    wire [7:0] uart_rx_data;
    wire       uart_tx_full, uart_rx_empty;
    wire [4:0] uart_tx_cnt, uart_rx_cnt;
    wire [7:0] uart_rx_err;
    reg        uart_tx_wr, uart_rx_rd;

    // BOTH HIGH is the run state: EN high = not held in reset, IO0 high =
    // boot from flash. A panel that is wired up but never addressed therefore
    // behaves as though this block were not here.
    //
    // WAS 2'b01, WHICH WAS BACKWARDS, with a comment asserting "IO0 low =
    // normal boot". It is the other way round: on ESP32 GPIO0 LOW at reset
    // selects the ROM download mode and HIGH boots from flash. Confirmed on
    // the bench 2026-09-01 -- the board reports boot:0x13 SPI_FAST_FLASH_BOOT
    // precisely because its pull-up holds IO0 high.
    //
    // The old default would have driven IO0 low and held the panel in
    // download mode forever: it would have powered up, shown nothing, and
    // never run its firmware. Latent only because EN/IO0 are not yet wired
    // (P5 does not carry them), which is exactly the wiring now being
    // considered -- so this had to be fixed before it could bite.
    reg  [1:0] esp_ctrl_r = 2'b11;

    assign cyd_esp_en  = esp_ctrl_r[0];
    assign cyd_esp_io0 = esp_ctrl_r[1];

    // Instantiated unconditionally. On its own pins it conflicts with
    // nothing, so one bitstream serves either panel and a CYD can be brought
    // up without disturbing a working display. It costs a few dozen LUTs
    // against the 73,711 this design already uses.
    uart_bridge #(
        .CLK_HZ (50_000_000),   // bus_clk, sys_clk_50m straight through
        .BAUD   (115200),
        .FIFO_AW(4)
    ) uart_i (
        .clk     (bus_clk),
        .rst_n   (bus_rst_n),
        .tx_wr   (uart_tx_wr),
        .tx_data (wdata_latched[7:0]),
        .tx_full (uart_tx_full),
        .rx_rd   (uart_rx_rd),
        .rx_data (uart_rx_data),
        .rx_empty(uart_rx_empty),
        .tx_count(uart_tx_cnt),
        .rx_count(uart_rx_cnt),
        .rx_err  (uart_rx_err),
        .uart_tx (cyd_uart_tx),
        .uart_rx (cyd_uart_rx)
    );

    always @(posedge bus_clk or negedge bus_rst_n) begin
        if (!bus_rst_n) begin
            spi_shift     <= 24'h0;
            spi_rx        <= 24'h0;
            spi_bits      <= 6'd0;
            spi_cs_touch_n <= 1'b1;
            spi_rx_en     <= 1'b0;
            spi_div       <= 5'd0;
            spi_div_max   <= SPI_DIV_LCD;
            spi_is_touch  <= 1'b0;
            lcd_req_seen  <= 1'b0;
            touch_irq_sync <= 2'b11;   // idle high = not pressed
            spi_busy      <= 1'b0;
            spi_dc        <= 1'b0;
            spi_cs_lcd_n  <= 1'b1;
            spi_sclk      <= 1'b0;
            spi_mosi      <= 1'b0;
            lcd_rst_n_r   <= 1'b0;   // hold the panel in reset
            lcd_bl_r      <= 1'b0;   // backlight off until configured
            touch_x       <= 12'h0;
            touch_y       <= 12'h0;
            touch_pressed <= 1'b0;
            touch_state   <= T_IDLE;
            touch_tick    <= 20'd0;
            touch_start   <= 1'b0;
            touch_ctrl    <= 8'h00;
        end else begin
            if (lcd_pending && !spi_busy) begin
                // Left-align into the 24-bit shifter: bit 23 goes out first.
                spi_shift    <= lcd_start_16 ? {lcd_start_data, 8'h00}
                                             : {lcd_start_data[7:0], 16'h0000};
                spi_bits     <= lcd_start_16 ? 6'd16 : 6'd8;
                spi_dc       <= lcd_start_dc;
                spi_cs_lcd_n <= 1'b0;
                spi_rx_en    <= 1'b0;
                spi_is_touch <= 1'b0;
                spi_div_max  <= SPI_DIV_LCD;
                spi_busy     <= 1'b1;
                spi_div      <= 5'd0;
                spi_sclk     <= 1'b0;
                // Present the first bit immediately, while SCLK is still low.
                spi_mosi     <= lcd_start_16 ? lcd_start_data[15]
                                             : lcd_start_data[7];
                // Consume the request. One driver each: the bus FSM owns
                // lcd_req_toggle, this block owns lcd_req_seen.
                lcd_req_seen <= lcd_req_toggle;
            end else if (touch_start && !spi_busy && !lcd_pending) begin
                // XPT2046: control byte then 16 clocks for the result. Held
                // off while a panel write is pending so the panel never waits
                // on touch -- and, because a dropped exchange would otherwise
                // latch a stale sample as a coordinate, touch_start is only
                // cleared when the transfer is actually taken (below).
                spi_shift      <= {touch_ctrl, 16'h0000};
                spi_bits       <= 6'd24;
                spi_dc         <= 1'b0;
                spi_cs_touch_n <= 1'b0;
                spi_rx_en      <= 1'b1;
                spi_rx         <= 24'h0;
                spi_is_touch   <= 1'b1;
                spi_div_max    <= SPI_DIV_TOUCH;
                spi_busy       <= 1'b1;
                spi_div        <= 5'd0;
                spi_sclk       <= 1'b0;
                spi_mosi       <= touch_ctrl[7];
                touch_start    <= 1'b0;
            end else if (spi_busy) begin
                spi_div <= spi_div + 5'd1;
                if (spi_div == spi_div_max) begin
                    spi_div <= 5'd0;
                    if (!spi_sclk) begin
                        // RISING edge. MOSI was set a full half-period ago, so
                        // the slave sees it stable -- previously MOSI and SCLK
                        // were assigned in the same cycle, giving zero setup
                        // while the comment claimed the opposite.
                        spi_sclk <= 1'b1;
                        // Mode 0: the slave presents its bit before this edge.
                        if (spi_rx_en)
                            spi_rx <= {spi_rx[22:0], lcd_miso};
                    end else begin
                        // FALLING edge: advance the shifter and present the
                        // next bit, which then has a half-period to settle.
                        spi_sclk  <= 1'b0;
                        spi_shift <= {spi_shift[22:0], 1'b0};
                        spi_mosi  <= spi_shift[22];
                        spi_bits  <= spi_bits - 6'd1;
                        if (spi_bits == 6'd1) begin
                            spi_busy       <= 1'b0;
                            spi_cs_lcd_n   <= 1'b1;
                            spi_cs_touch_n <= 1'b1;
                        end
                    end
                end
            end

            if (lcd_ctrl_wr) begin
                lcd_rst_n_r <= lcd_ctrl_data[0];
                lcd_bl_r    <= lcd_ctrl_data[1];
            end

            // XPT2046 PENIRQ is active low, open drain, and asynchronous to
            // bus_clk -- hence the two-flop synchroniser rather than sampling
            // the pad straight into a register that now gates an FSM.
            touch_irq_sync <= {touch_irq_sync[0], touch_irq};
            touch_pressed  <= ~touch_irq_sync[1];

            // ---- touch sequencer ----------------------------------------
            // touch_start is now cleared by the SPI engine when it actually
            // TAKES the transfer, not merely when the shifter looks busy.
            // Clearing it on "busy" meant a request lost to a panel write
            // vanished, and the FSM then advanced anyway and latched whatever
            // spi_rx happened to hold -- a stale sample reported as a real
            // coordinate, which is worse than reporting nothing.

            if (touch_tick != 20'd0)
                touch_tick <= touch_tick - 20'd1;

            case (touch_state)
                T_IDLE: begin
                    // Only poll while the pen is actually down. PENIRQ is the
                    // panel's own indication, so an untouched screen costs no
                    // SPI traffic at all.
                    if (touch_pressed && touch_tick == 20'd0 &&
                        !spi_busy && !lcd_pending && !touch_start) begin
                        touch_ctrl  <= XPT_CMD_X;
                        touch_start <= 1'b1;
                        touch_state <= T_READ_X;
                    end
                end
                T_READ_X: begin
                    // Advance only when a TOUCH transfer completed. If the
                    // request is still queued (touch_start high) it was held
                    // off by a panel write and will go later; if the finished
                    // transfer was the panel's, spi_rx is not ours.
                    if (!touch_start && !spi_busy && spi_is_touch) begin
                        // Of the 16 clocks after the control byte the result
                        // is bits 14:3 -- one busy clock, then 12 data bits.
                        touch_x     <= spi_rx[14:3];
                        touch_ctrl  <= XPT_CMD_Y;
                        touch_start <= 1'b1;
                        touch_state <= T_READ_Y;
                    end
                end
                T_READ_Y: begin
                    if (!touch_start && !spi_busy && spi_is_touch) begin
                        touch_y     <= spi_rx[14:3];
                        touch_state <= T_SETTLE;
                    end
                end
                T_SETTLE: begin
                    // 10ms between rounds. bus_clk is 50MHz, so that is
                    // 500,000 cycles -- the previous value assumed 100MHz and
                    // therefore polled at 20ms, half the intended rate.
                    touch_tick  <= 20'd500000;
                    touch_state <= T_IDLE;
                end
                default: touch_state <= T_IDLE;
            endcase
        end
    end

    // =====================================================================
    // Fan control -- closed loop on die temperature, entirely in fabric.
    //
    // Thresholds are compared against the RAW XADC code to keep this to
    // magnitude comparators; no conversion arithmetic in fabric.
    //     code = (degC + 273.15) * 4096 / 503.975, then << 4
    //       40C -> 16'h9F10   55C -> 16'hA6E0
    //       70C -> 16'hAEB0   85C -> 16'hB680
    //
    // FAIL-SAFE: a raw code of 0 means the XADC has not produced a reading
    // yet (or is not working). That runs the fan at 100%, not 0% -- an
    // unknown temperature must never be treated as a cold one.
    // =====================================================================
    localparam [15:0] TEMP_40C = 16'h9F10;
    localparam [15:0] TEMP_55C = 16'hA6E0;
    localparam [15:0] TEMP_70C = 16'hAEB0;
    localparam [15:0] TEMP_85C = 16'hB680;

    reg  [7:0]  fan_duty;        // 0-255, what we are actually driving
    reg  [7:0]  fan_floor;       // host-settable minimum, 0 = pure auto
    reg  [10:0] fan_pwm_cnt;
    reg  [7:0]  fan_tach_hz;     // tach pulses in the last second
    reg  [7:0]  fan_tach_acc;
    reg  [25:0] fan_sec_cnt;
    reg  [2:0]  tach_sync;

    wire [7:0] fan_auto =
          (xadc_temp_bus == 16'h0000) ? 8'd255 :   // unknown -> full
          (xadc_temp_bus >= TEMP_85C) ? 8'd255 :
          (xadc_temp_bus >= TEMP_70C) ? 8'd191 :
          (xadc_temp_bus >= TEMP_55C) ? 8'd140 :
          (xadc_temp_bus >= TEMP_40C) ? 8'd102 :
                                        8'd77;    // ~30% floor, never off

    always @(posedge bus_clk or negedge bus_rst_n) begin
        if (!bus_rst_n) begin
            fan_duty     <= 8'd255;   // full until we know better
            // fan_floor is NOT reset here. It is written by the bus state
            // machine (ADDR_FAN), and a register driven from two always blocks
            // is a multiple-driver conflict -- yosys reported exactly that on
            // all 8 bits. This block only READS it, which is fine; ownership
            // sits with the block that writes it, and the reset went with it.
            fan_pwm_cnt  <= 11'd0;
            fan_sec_cnt  <= 26'd0;
            fan_tach_acc <= 8'd0;
            fan_tach_hz  <= 8'd0;
            tach_sync    <= 3'b000;
        end else begin
            fan_duty    <= (fan_auto > fan_floor) ? fan_auto : fan_floor;
            fan_pwm_cnt <= fan_pwm_cnt + 11'd1;   // free-running, wraps

            // Tach: count rising edges over one second of bus_clk.
            tach_sync <= {tach_sync[1:0], fan_tach_in};
            if (tach_sync[2:1] == 2'b01 && fan_tach_acc != 8'hFF)
                fan_tach_acc <= fan_tach_acc + 8'd1;

            if (fan_sec_cnt >= 26'd49_999_999) begin
                fan_sec_cnt  <= 26'd0;
                fan_tach_hz  <= fan_tach_acc;
                fan_tach_acc <= 8'd0;
            end else begin
                fan_sec_cnt <= fan_sec_cnt + 26'd1;
            end
        end
    end

    // 50MHz / 2048 = 24.4kHz, inside the 21-28kHz a 4-pin PWM fan expects.
    // duty<<3 spreads 0-255 across the 0-2047 counter without a divide.
    assign fan_pwm = (fan_pwm_cnt < {fan_duty, 3'b000});

    // =====================================================================
    // Bus-side state machine: 4-phase interlocked handshake, one
    // register access at a time.
    // =====================================================================
    localparam S_IDLE  = 2'd0,
               S_WRITE = 2'd1,
               S_READ  = 2'd2;

    reg [1:0]  bus_state;
    reg [4:0]  addr_latched;
    reg [15:0] wdata_latched;
    reg [15:0] header_lo_stage, target_lo_stage;
    reg        request_issued;
    reg [15:0] rdata_reg;
    reg        gpio_data_oe;

    // Status/nonce values, already synchronized into bus_clk further down.
    wire        hash_active_bus;
    wire        nonce_valid_bus;
    wire [31:0] golden_nonce_bus;
    reg         nonce_valid_clear_pulse;

    // Synchronous reset deliberately -- see the sync-vs-async note above
    // wr_sync/rd_sync's always block; same reasoning applies here.
    always @(posedge bus_clk) begin
        if (!bus_rst_n) begin
            bus_state       <= S_IDLE;
            gpio_ready      <= 1'b0;
            gpio_data_oe    <= 1'b0;
            request_issued  <= 1'b0;
            // NOTE: req_toggle_bus is deliberately NOT reset here.
            //
            // It is a toggle, not a state -- only its TRANSITIONS carry meaning,
            // and the clk_h receiver detects them as req_sync2_h ^ req_sync3_h.
            // Forcing it to 0 on reset creates an edge if it happened to be 1,
            // which fires one spurious request on the clk_h side carrying stale
            // req_op_bus/req_data_bus. Because odo_block_data is a plain 19-deep
            // shift register with no word counter and no position reset, a single
            // extra get_block_pulse_h shifts the entire header by one 32-bit word
            // -- after which the miner runs normally and every result is wrong,
            // with no recovery path (OP_SOFT_RESET clears the word counters but
            // not the shift-register position).
            //
            // The clk_h synchroniser has no reset of its own, so leaving this
            // undisturbed is what keeps the two sides consistent across a bus
            // reset. Do not "tidy" this into the reset list.
            // lcd_req_toggle IS reset, unlike req_toggle_bus above, and the
            // difference matters. req_toggle_bus crosses into clk_h, whose
            // synchroniser has no reset, so forcing it creates an edge the far
            // side sees as a real request. lcd_req_toggle and its receiver
            // lcd_req_seen are both in bus_clk and both cleared by bus_rst_n,
            // so they come out of reset agreeing. Resetting only one of them
            // would be the bug: lcd_pending would read true and fire one
            // spurious panel write.
            lcd_req_toggle  <= 1'b0;
            header_lo_stage <= 16'h0;
            target_lo_stage <= 16'h0;
            nonce_valid_clear_pulse <= 1'b0;
            // Host-settable fan floor. Owned here because this block writes it
            // (S_WRITE/ADDR_FAN); the fan controller only reads it.
            //
            // 0 means "pure auto", which is the safe default: the automatic
            // curve never falls below ~30% duty, so a zeroed floor cannot stop
            // the fan. This reset is synchronous while the fan block's is
            // asynchronous, so fan_floor now clears one bus_clk later than it
            // used to. That is harmless -- fan_duty resets to 255 (full) and
            // the PWM period is 2048 cycles, so a single stale cycle cannot
            // show up as reduced cooling.
            fan_floor       <= 8'd0;
        end else begin
            nonce_valid_clear_pulse <= 1'b0;
            // Defaulted low every cycle. THAT ALONE DOES NOT MAKE A
            // ONE-SHOT, and believing it did was a real bug: S_WRITE
            // re-executes its case on EVERY bus_clk until the CM4 releases
            // WR_N, so a case body that sets a strobe re-asserts it every
            // cycle and the default never wins. Measured in simulation on the
            // real wrapper: one host write to ADDR_UART_DATA pushed the byte
            // 4 times with WR_N released instantly and 16 times (FIFO full)
            // at the ~20us a real CM4 syscall takes.
            //
            // Two disciplines actually work, and both are used here:
            //   - fire at END of transaction, inside the
            //     `if (gpio_ready && !rd_sync[2])` block -- what the READ
            //     path does for uart_rx_rd and the nonce ack
            //   - guard the case body with `request_issued`, cleared in
            //     S_IDLE -- what the clk_h handshake writes do, and now the
            //     UART and LCD writes too
            //
            // nonce_valid_clear_pulse is NOT a one-shot despite its name --
            // see the note where it is consumed -- and that difference cost a
            // torn nonce read in 0x0200.
            uart_tx_wr <= 1'b0;
            uart_rx_rd <= 1'b0;

            case (bus_state)
                S_IDLE: begin
                    gpio_ready   <= 1'b0;
                    gpio_data_oe <= 1'b0;
                    request_issued <= 1'b0;
                    // One-shot strobe into the display block. lcd_start used
                    // to be cleared here too, which is precisely what made it
                    // useless: S_IDLE is not reached until the CM4 releases
                    // WR_N, long after the transfer finished. It is a toggle
                    // now and needs no clearing.
                    lcd_ctrl_wr  <= 1'b0;
                    if (wr_active) begin
                        addr_latched  <= addr_sync1;
                        wdata_latched <= data_in_sync1;
                        bus_state     <= S_WRITE;
                    end else if (rd_active) begin
                        addr_latched <= addr_sync1;
                        bus_state    <= S_READ;
                    end
                end

                S_WRITE: begin
                    case (addr_latched)
                        // Minimum fan duty. Purely a floor: the automatic
                        // curve still applies above it, so the host can raise
                        // cooling but never disable it.
                        ADDR_FAN: begin
                            fan_floor  <= wdata_latched[7:0];
                            gpio_ready <= 1'b1;
                        end
                        // Display writes are dropped if the shifter is still
                        // busy; the host polls LCD_STAT before writing.
                        ADDR_LCD_CMD: begin
                            // ONE-SHOT via request_issued -- see the note at
                            // the strobe defaults. Without it lcd_req_toggle
                            // flipped on every cycle of S_WRITE, starting 16
                            // SPI transfers per host write. !spi_busy does not
                            // prevent that: the duplication happens WITHIN one
                            // transaction, while spi_busy gates between them.
                            if (!request_issued && !spi_busy) begin
                                lcd_start_data <= wdata_latched;
                                lcd_start_dc   <= 1'b0;
                                lcd_start_16   <= 1'b0;
                                lcd_req_toggle <= ~lcd_req_toggle;
                                request_issued <= 1'b1;
                            end
                            gpio_ready <= 1'b1;
                        end
                        ADDR_LCD_DATA: begin
                            // ONE-SHOT via request_issued -- see the note at
                            // the strobe defaults. Without it lcd_req_toggle
                            // flipped on every cycle of S_WRITE, starting 16
                            // SPI transfers per host write. !spi_busy does not
                            // prevent that: the duplication happens WITHIN one
                            // transaction, while spi_busy gates between them.
                            if (!request_issued && !spi_busy) begin
                                lcd_start_data <= wdata_latched;
                                lcd_start_dc   <= 1'b1;
                                lcd_start_16   <= 1'b1;
                                lcd_req_toggle <= ~lcd_req_toggle;
                                request_issued <= 1'b1;
                            end
                            gpio_ready <= 1'b1;
                        end
                        ADDR_LCD_DATA8: begin
                            // ONE-SHOT via request_issued -- see the note at
                            // the strobe defaults. Without it lcd_req_toggle
                            // flipped on every cycle of S_WRITE, starting 16
                            // SPI transfers per host write. !spi_busy does not
                            // prevent that: the duplication happens WITHIN one
                            // transaction, while spi_busy gates between them.
                            if (!request_issued && !spi_busy) begin
                                lcd_start_data <= wdata_latched;
                                lcd_start_dc   <= 1'b1;
                                lcd_start_16   <= 1'b0;
                                lcd_req_toggle <= ~lcd_req_toggle;
                                request_issued <= 1'b1;
                            end
                            gpio_ready <= 1'b1;
                        end
                        ADDR_UART_DATA: begin
                            // request_issued makes this fire ONCE. Without it
                            // the byte was pushed on every cycle of S_WRITE --
                            // 4 to 16 copies per host write, so the panel
                            // received an unbroken run of one character and
                            // could never assemble a line.
                            if (!request_issued) begin
                                if (!uart_tx_full) uart_tx_wr <= 1'b1;
                                request_issued <= 1'b1;
                            end
                            // A write into a full FIFO is dropped. The host
                            // can read UART_STAT first; blocking the bus here
                            // would stall the miner's register traffic for a
                            // panel, which is the wrong thing to prioritise.
                            gpio_ready <= 1'b1;
                        end
                        ADDR_ESP_CTRL: begin
                            esp_ctrl_r <= wdata_latched[1:0];
                            gpio_ready <= 1'b1;
                        end
                        ADDR_LCD_CTRL: begin
                            lcd_ctrl_data <= wdata_latched;
                            lcd_ctrl_wr   <= 1'b1;
                            gpio_ready    <= 1'b1;
                        end
                        ADDR_CTRL: begin
                            if (!request_issued) begin
                                req_op_bus     <= wdata_latched[1] ? OP_HOST_BREAK : OP_SOFT_RESET;
                                req_data_bus   <= {16'h0, wdata_latched};
                                req_toggle_bus <= ~req_toggle_bus;
                                request_issued <= 1'b1;
                            end else if (ack_pulse_bus) begin
                                gpio_ready <= 1'b1;
                            end
                        end
                        ADDR_HEADER_LO: begin
                            header_lo_stage <= wdata_latched;
                            gpio_ready      <= 1'b1; // staging only, no clk_h side effect
                        end
                        ADDR_HEADER_HI: begin
                            if (!request_issued) begin
                                req_op_bus     <= OP_HEADER_WORD;
                                req_data_bus   <= {wdata_latched, header_lo_stage};
                                req_toggle_bus <= ~req_toggle_bus;
                                request_issued <= 1'b1;
                            end else if (ack_pulse_bus) begin
                                gpio_ready <= 1'b1;
                            end
                        end
                        ADDR_TARGET_LO: begin
                            target_lo_stage <= wdata_latched;
                            gpio_ready      <= 1'b1; // staging only
                        end
                        ADDR_TARGET_HI: begin
                            if (!request_issued) begin
                                req_op_bus     <= OP_TARGET_WORD;
                                req_data_bus   <= {wdata_latched, target_lo_stage};
                                req_toggle_bus <= ~req_toggle_bus;
                                request_issued <= 1'b1;
                            end else if (ack_pulse_bus) begin
                                gpio_ready <= 1'b1;
                            end
                        end
                        default: begin
                            // Write to a read-only/unmapped address: ack, no effect.
                            gpio_ready <= 1'b1;
                        end
                    endcase

                    if (gpio_ready && !wr_sync[2]) begin
                        // CM4 released WR_N after seeing READY (wr_sync is
                        // active-high, so "released" is 0, not 1 -- see
                        // its declaration comment).
                        gpio_ready <= 1'b0;
                        bus_state  <= S_IDLE;
                    end
                end

                S_READ: begin
                    case (addr_latched)
                        ADDR_VERSION:  rdata_reg <= VERSION;
                        ADDR_STATUS:   rdata_reg <= {14'h0, nonce_valid_bus, hash_active_bus};
                        ADDR_NONCE_LO: rdata_reg <= golden_nonce_bus[15:0];
                        // NOTE: the consume/ack for this read fires when the
                        // transaction ENDS, below -- not here. See the comment
                        // at that assignment.
                        ADDR_NONCE_HI: rdata_reg <= golden_nonce_bus[31:16];
                        ADDR_SEED_LO:  rdata_reg <= ODO_SEED[15:0];
                        ADDR_SEED_HI:  rdata_reg <= ODO_SEED[31:16];
                        ADDR_TEMP:     rdata_reg <= xadc_temp_bus;
                        ADDR_VCCINT:   rdata_reg <= xadc_vccint_bus;
                        ADDR_VCCAUX:   rdata_reg <= xadc_vccaux_bus;
                        ADDR_VCCBRAM:  rdata_reg <= xadc_vccbram_bus;
                        ADDR_FAN:      rdata_reg <= {fan_tach_hz, fan_duty};
                        ADDR_LCD_STAT: rdata_reg <= {15'h0, spi_busy};
                        ADDR_TOUCH_X:  rdata_reg <= {4'h0, touch_x};
                        ADDR_TOUCH_Y:  rdata_reg <= {4'h0, touch_y};
                        ADDR_TOUCH_STAT: rdata_reg <= {15'h0, touch_pressed};
                        // 8 + 4 + 4 = 16. The depth field is 4 bits, which
                        // is exactly enough for an 8-deep FIFO's 0..8.
                        ADDR_UART_DATA: begin
                            rdata_reg <= {8'h0, uart_rx_data};
                            // Popped at the END of the transaction, below --
                            // NOT here. S_READ lasts as long as the CM4 holds
                            // RD_N, and popping on every cycle of it would
                            // discard most of the FIFO. Exactly the bug that
                            // ADDR_NONCE_HI had in 0x0200.
                        end
                        // {rx_err[3:0], tx_cnt[4:0], rx_cnt[4:0],
                        //  tx_full, rx_empty}  -- 4+5+5+1+1 = 16.
                        //
                        // CHANGED AT 0x0203, because the previous layout
                        // could not answer the one question the host has to
                        // ask before writing. It was
                        //   {rx_err[7:0], rx_cnt[3:0], tx_cnt[2:0], rx_empty}
                        // with a 16-deep TX FIFO -- so a 5-bit count was
                        // truncated to 3 bits and depths 0, 8 and 16 read
                        // identically, and there was NO tx_full bit at all.
                        // The write path drops into a full FIFO silently, and
                        // the comment there told the host to "read UART_STAT
                        // first", which UART_STAT could not actually answer.
                        // For esptool that is fatal: a dropped byte corrupts
                        // the protocol with no indication.
                        //
                        // Both counts are now exact, so the host can write
                        // (16 - tx_cnt) bytes in one go instead of creeping
                        // along one at a time. rx_err drops to 4 bits and
                        // still saturates -- it is a "framing errors are
                        // happening" flag, and 15 says that as well as 255.
                        ADDR_UART_STAT: rdata_reg <=
                            {uart_rx_err[3:0], uart_tx_cnt, uart_rx_cnt,
                             uart_tx_full, uart_rx_empty};
                        ADDR_FIFO_STAT: rdata_reg <=
                            {lost_sync2_bus, 4'h0, fifocnt_sync2_bus};
                        default: rdata_reg <= 16'h0;
                    endcase
                    gpio_data_oe <= 1'b1;
                    gpio_ready   <= 1'b1;

                    if (gpio_ready && !rd_sync[2]) begin
                        // CM4 released RD_N after seeing READY (rd_sync is
                        // active-high -- see wr_sync's declaration comment).
                        gpio_ready   <= 1'b0;
                        gpio_data_oe <= 1'b0;
                        bus_state    <= S_IDLE;

                        // CONSUME THE NONCE HERE, AT THE END OF THE READ.
                        //
                        // This used to fire inside the ADDR_NONCE_HI case
                        // above, i.e. on the FIRST cycle of S_READ. Harmless
                        // when all it did was clear a level. Not harmless in
                        // v2.0, where it also ACKs the found-FIFO handoff:
                        //
                        //   host reads NONCE_LO            (gets nonce A low)
                        //   host asserts RD_N for NONCE_HI
                        //     -> ack fires immediately
                        //     -> clk_h pops nonce B into the latch
                        //     -> golden_nonce_reg becomes B, and rdata_reg
                        //        follows it, DURING the same read
                        //   host samples                   (gets nonce B high)
                        //
                        // and the host walks away with A's low half and B's
                        // high half. S_READ lasts as long as the CM4 holds
                        // RD_N, which over a bit-banged GPIO bus is
                        // microseconds -- ample time.
                        //
                        // MEASURED 2026-08-31: this reproduced exactly. Runs
                        // with a FIFO backlog failed their first N nonces
                        // (N ~ the backlog depth, because each ack instantly
                        // supplied a replacement mid-read) and then passed
                        // every subsequent one once finds became rarer than
                        // the drain. Every passing hash was genuinely tiny;
                        // every failing one was two halves of different
                        // nonces, so it hashed to nothing in particular.
                        //
                        // Deferring to end-of-transaction means the clk_h side
                        // cannot touch the latch until the host has both
                        // halves, which is what makes the 32-bit value atomic
                        // across a 16-bit bus.
                        if (addr_latched == ADDR_NONCE_HI)
                            nonce_valid_clear_pulse <= 1'b1;
                        // Same reasoning, same place: consume once, when the
                        // host has actually taken the byte.
                        if (addr_latched == ADDR_UART_DATA && !uart_rx_empty)
                            uart_rx_rd <= 1'b1;
                    end
                end

                default: bus_state <= S_IDLE;
            endcase
        end
    end

    assign gpio_data = gpio_data_oe ? rdata_reg : 16'bz;

    // =====================================================================
    // Hash-core (clk_h) domain: decode the request into the shift pulses
    // odo_block_data expects, and commit a completed job into the snapshot
    // registers the free-running cores read.
    //
    // Up to v1.9 this mirrored atomminer_odocrypt.v (and the Zynq wrapper)
    // verbatim, including its arm-on-8th-target-word behaviour. v2.0 keeps
    // the bus protocol identical but turns that arm into a COMMIT -- see
    // commit_arm_h.
    // =====================================================================
    reg [31:0] data_from_host_h;
    reg        get_block_pulse_h;
    reg        get_target_pulse_h;
    reg        host_break_pulse_h;
    // One-cycle resync pulse for found_path, from OP_SOFT_RESET.
    reg found_soft_reset_h = 1'b0;

    reg [4:0]  header_word_cnt_h; // 0..18, 19 words total
    // THREE bits, not four. MEASURED ON HARDWARE 2026-08-30.
    //
    // This was reg [3:0] while being compared against 7, so it wrapped at 16
    // and nothing resets it between jobs. Dispatch 1 walks counts 0..7 and arms
    // start_hash on the 8th word; dispatch 2 walks 8..15, never equals 7, and
    // NEVER ARMS THE CORE; dispatch 3 arms again. The miner was hashing on
    // every OTHER job and idle in between.
    //
    // The comment on the old line said "0..7, 8 words total", which is what the
    // code intended and not what a 4-bit register does. Width and comment
    // disagreed and the width won.
    //
    // Symptoms this explains exactly:
    //   * odo-miner reporting "found=10 shares=0 stale=10" over 95 s -- jobs
    //     arrived every 5-10 s, half of them armed, so ~10 finds
    //   * every one of those counted stale: on a dispatch that did not arm, the
    //     found-latch still held the PREVIOUS job's nonce, the host read it and
    //     checked it against the NEW header, and it failed
    //   * am01_smoke alternating between one find and none on consecutive runs
    //
    // Proven by working around it before fixing it: dispatching twice covers
    // both parities, and with that am01_smoke returned 6 nonces out of 6 valid
    // against a 1-in-256 target. Six chance passes would be 1 in 2.8e14.
    reg [2:0]  target_word_cnt_h; // 0..7, wraps at 8 -- see above

    // COMMIT, not ARM. v2.0 replaced the AtomMiner core (miner.v, halts on
    // every find and must be re-armed) with the free-running miner_pipelined.
    // There is no start_hash and nothing to arm: the cores hash continuously
    // from configuration. What the 8th target word now does is COMMIT the
    // freshly-shifted-in job into the snapshot registers the cores actually
    // read (header_committed_h / target_committed_h below).
    //
    // commit_arm_h delays the commit by exactly one cycle. odo_block_data
    // shifts on posedge clk_h when get_target_in is high, so the 8th target
    // word only lands at the END of the cycle in which get_target_pulse_h is
    // asserted -- snapshotting in that same cycle would capture a target
    // still missing its last word.
    reg        commit_arm_h   = 1'b0;
    reg        commit_pulse_h = 1'b0;

    always @(posedge clk_h) begin
        get_block_pulse_h  <= 1'b0;
        get_target_pulse_h <= 1'b0;
        host_break_pulse_h <= 1'b0;
        found_soft_reset_h <= 1'b0;   // one cycle only, like the pulses above
        commit_arm_h       <= 1'b0;
        commit_pulse_h     <= commit_arm_h;

        if (req_pulse_h) begin
            data_from_host_h <= req_data_bus;
            case (req_op_bus)
                OP_HEADER_WORD: begin
                    get_block_pulse_h <= 1'b1;
                    header_word_cnt_h <= header_word_cnt_h + 1'b1;
                end
                OP_TARGET_WORD: begin
                    get_target_pulse_h <= 1'b1;
                    target_word_cnt_h  <= target_word_cnt_h + 1'b1;
                    if (target_word_cnt_h == 3'd7)
                        commit_arm_h <= 1'b1; // 8th (last) word completes the job
                end
                // Accepted and ignored. A v1.x host still sets CTRL bit 1 to
                // request a host break; with a free-running core there is
                // nothing to break. Kept as an explicit no-op rather than
                // deleted so an older host cannot fall through to a case
                // default and have its write silently mean something else.
                OP_HOST_BREAK: begin
                    host_break_pulse_h <= 1'b1;
                end
                OP_SOFT_RESET: begin
                    header_word_cnt_h <= 5'h0;
                    target_word_cnt_h <= 3'h0;
                    // Also resync the found path. Before 2026-09-01 this
                    // opcode could not reach it, and found_path had no reset
                    // at all -- so a host killed between a nonce handover and
                    // its ack latched `busy` forever, stalling every
                    // subsequent find. Nothing short of reconfiguring the
                    // FPGA cleared it, which cost an hour of mining. See the
                    // soft_reset comment in found_path.v and TODO item 8.
                    found_soft_reset_h <= 1'b1;
                end
            endcase
        end
    end

    wire [607:0] header;
    wire [255:0] target;

    odo_block_data odo_block_data_inst (
        .clk_h            (clk_h),
        .data_from_host_in(data_from_host_h),
        .get_midstate_in  (1'b0), // GPIO side collapses midstate/block into one FIFO
        .get_block_in     (get_block_pulse_h),
        .get_target_in    (get_target_pulse_h),
        .header           (header),
        .target           (target)
    );

    // -----------------------------------------------------------------
    // COMMITTED JOB SNAPSHOT -- new in v2.0, and mandatory for a
    // free-running core.
    //
    // odo_block_data is a shift register: while the host is writing the 27
    // words of a dispatch, `header`/`target` are a moving mixture of the old
    // job and the new one. The AtomMiner core got away with reading them
    // directly because start_hash held it halted for the whole load. The
    // free-running core has no such gate -- it would spend the entire
    // 27-word load hashing half-written garbage, and worse, would report
    // finds against it.
    //
    // So the cores read these snapshot registers, never the shift register
    // directly. They change exactly once per dispatch, atomically, on
    // commit_pulse_h. This is also what makes the CDC below sound: the data
    // the cores see is stable between commits by construction.
    reg [607:0] header_committed_h = 608'h0;
    reg [255:0] target_committed_h = 256'h0;

    always @(posedge clk_h) begin
        if (commit_pulse_h) begin
            header_committed_h <= header;
            target_committed_h <= target;
        end
    end

    // -----------------------------------------------------------------
    // Hash-core bank. NUM_MINERS instances share one work item, each
    // sweeping its own slice of the 32-bit nonce space via NONCE_BASE.
    //
    // Why more than one: a single instance uses 420 RAMB18 of this
    // chip's 890 (measured -- they are OdoCrypt's large S-boxes), i.e.
    // it leaves nearly half the block RAM idle while using only ~9% of
    // the logic. Total hashrate here is BRAM-bound at roughly
    // 0.5 x Fmax, and one instance only reaches half of that. See
    // ../README.md "Expected hashrate".
    //
    // NUM_MINERS=2 fills the BRAM budget. MEASURED by walking the
    // synthesised hierarchy (not estimated): 1 instance = 420 RAMB18
    // (47.2% of the XC7K325T's 890), 2 instances = 840 (94.4%) -- fits,
    // with 50 RAMB18 spare. 3 would need 1260 and cannot fit. Do not
    // raise this without re-measuring.
    // -----------------------------------------------------------------
    // ONE phase for the whole design, not one per S-box. Every muxed
    // S-box has to interleave identically: two that were out of step
    // would drive the same table in the same clk2x window and read
    // each other's addresses. Toggling on clk_2x makes it high for
    // exactly the half of each clk_h period that serves slot 1.
    reg sbox_mux_phase = 1'b0;
    always @(posedge clk_2x)
        sbox_mux_phase <= ~sbox_mux_phase;

    wire [NUM_MINERS-1:0] found_arr;
    wire [31:0]           nonce_arr [0:NUM_MINERS-1];

    genvar gi;
    generate
        for (gi = 0; gi < NUM_MINERS; gi = gi + 1) begin : g_miner
            miner_pipelined_mux4 #(
                // Even split of the nonce space: instance gi sweeps
                // [gi*span, (gi+1)*span). For NUM_MINERS=2 that is
                // 0x00000000 and 0x80000000. Same convention miner.v called
                // NONCE_BASE; the free-running core spells it INONCE.
                .INONCE(gi * ((32'hFFFFFFFF / NUM_MINERS) + 32'h1))
            ) miner_inst (
                .clk   (clk_h),
                .clk2x (clk_2x),
                .phase (sbox_mux_phase),
                // The SNAPSHOT, never odo_block_data's shift register --
                // see the header_committed_h comment above.
                .header(header_committed_h),
                .target(target_committed_h),
                .nonce (nonce_arr[gi]),
                .found (found_arr[gi])
            );
        end
    endgenerate

    // -----------------------------------------------------------------
    // Result path: settle window, found FIFO, and the handoff to bus_clk.
    //
    // Lives in found_path.v rather than inline here specifically so it can be
    // simulated without the cipher. Four bitstreams in a row shipped a bug in
    // this logic (0x0106..0x0109) and every one of them was found on hardware
    // rather than in simulation, because exercising it inline meant
    // elaborating two 15.5k-line odo_encrypt pipelines. tb_found_path drives
    // the extracted module directly and runs in under a second.
    //
    // SETTLE_CYCLES is 4096, unchanged in value from v1.7 but now hung off the
    // job COMMIT instead of start_hash, because there is no longer an arm to
    // hang it off. odo-miner-cyclonev's pipelined_miner_top.v uses the same
    // number for the same reason: after a commit the pipeline still holds
    // in-flight nonces hashed with the PREVIOUS header, those drain over the
    // pipeline latency, and they can spuriously qualify against the new
    // target. At the 205 cycles v1.6 inherited from the AtomMiner reference
    // the window closed while they were still draining, which is what made
    // the first find after every arm a previous-header result wearing a
    // new-sweep nonce.
    //
    // It does NOT gate the cores' nonce counters -- see found_path.v.
    wire [32*NUM_MINERS-1:0] nonce_flat_h;
    genvar fj;
    generate
        for (fj = 0; fj < NUM_MINERS; fj = fj + 1) begin : g_flat
            assign nonce_flat_h[32*fj +: 32] = nonce_arr[fj];
        end
    endgenerate

    wire        report_ok_h;
    wire [7:0]  lost_count_h;
    wire [3:0]  fifo_count_h;
    wire        nonce_toggle_h;
    wire [31:0] golden_nonce_latch_h;

    // DECLARED HERE, NOT WITH THE BUS-SIDE REGISTERS ~20 LINES BELOW that
    // drive it. found_path's port connection reads it first, and an
    // undeclared identifier in a port connection creates an implicit 1-bit
    // net at the point of use; whether that net is then unified with the
    // later `reg` is tool-dependent. If it were not, found_path would see a
    // permanently-undriven ack, never clear its busy flag, and hand over
    // exactly one nonce ever -- with no error anywhere. This file already
    // carries the same note for host_break_debounced; iverilog warned about
    // this one, which is why the declaration moved rather than the warning
    // being filtered.
    reg         nonce_ack_toggle_bus = 1'b0;

    found_path #(
        .NUM_MINERS   (NUM_MINERS),
        .SETTLE_CYCLES(SETTLE_CYCLES_P),
        .FIFO_AW      (3)
    ) found_path_inst (
        .clk          (clk_h),
        .commit       (commit_pulse_h),
        .soft_reset   (found_soft_reset_h),
        .found_in     (found_arr),
        .nonce_in_flat(nonce_flat_h),
        .ack_toggle   (nonce_ack_toggle_bus),
        .nonce_toggle (nonce_toggle_h),
        .nonce_latch  (golden_nonce_latch_h),
        .report_ok    (report_ok_h),
        .lost_count   (lost_count_h),
        .fifo_count   (fifo_count_h)
    );

    (* ASYNC_REG = "TRUE" *) reg nonce_sync1_bus;
    reg nonce_sync2_bus, nonce_sync3_bus;
    (* ASYNC_REG = "TRUE" *) reg hash_active_sync1_bus;
    reg hash_active_sync2_bus;
    reg [31:0] golden_nonce_reg;
    reg        nonce_valid_reg;

    // Flipped when the host reads NONCE_HI, i.e. when it has taken the nonce
    // out of the latch. The clk_h side waits for this before handing over the
    // next FIFO entry -- see handoff_busy_h.

    // Telemetry only, and knowingly unsynchronised as a multi-bit bus: these
    // can tear if sampled mid-update, exactly like the XADC values above, and
    // for the same reason it is accepted here -- a torn read of a loss counter
    // is a cosmetically wrong number in a diagnostic register, not a
    // correctness problem. Nothing downstream makes a decision on it.
    (* ASYNC_REG = "TRUE" *) reg [7:0] lost_sync1_bus;
    reg [7:0] lost_sync2_bus;
    (* ASYNC_REG = "TRUE" *) reg [3:0] fifocnt_sync1_bus;
    reg [3:0] fifocnt_sync2_bus;

    wire nonce_new_pulse_bus = nonce_sync2_bus ^ nonce_sync3_bus;

    // Synchronous reset deliberately -- see the sync-vs-async note above
    // wr_sync/rd_sync's always block; same reasoning applies here.
    always @(posedge bus_clk) begin
        if (!bus_rst_n) begin
            nonce_sync1_bus <= 1'b0;
            nonce_sync2_bus <= 1'b0;
            nonce_sync3_bus <= 1'b0;
            hash_active_sync1_bus <= 1'b0;
            hash_active_sync2_bus <= 1'b0;
            nonce_valid_reg <= 1'b0;
            golden_nonce_reg <= 32'h0;
            nonce_ack_toggle_bus <= 1'b0;
            lost_sync1_bus <= 8'h0;
            lost_sync2_bus <= 8'h0;
            fifocnt_sync1_bus <= 4'h0;
            fifocnt_sync2_bus <= 4'h0;
        end else begin
            nonce_sync1_bus <= nonce_toggle_h;
            nonce_sync2_bus <= nonce_sync1_bus;
            nonce_sync3_bus <= nonce_sync2_bus;

            // v2.0: "hashing" no longer means "armed" -- the cores never stop.
            // What the host actually wants to know is whether the FPGA is
            // working on a committed job whose settle window has closed, i.e.
            // whether a find reported now would be trustworthy.
            hash_active_sync1_bus <= report_ok_h;
            hash_active_sync2_bus <= hash_active_sync1_bus;

            lost_sync1_bus    <= lost_count_h;
            lost_sync2_bus    <= lost_sync1_bus;
            fifocnt_sync1_bus <= fifo_count_h;
            fifocnt_sync2_bus <= fifocnt_sync1_bus;

            if (nonce_new_pulse_bus) begin
                golden_nonce_reg <= golden_nonce_latch_h;
                nonce_valid_reg  <= 1'b1;
            end else if (nonce_valid_clear_pulse && nonce_valid_reg) begin
                nonce_valid_reg  <= 1'b0;
                // Tell clk_h the latch is free.
                //
                // GATED ON nonce_valid_reg, and that is load-bearing.
                // nonce_valid_clear_pulse is NOT a one-cycle pulse despite the
                // name: S_READ persists until the CM4 releases RD_N, and the
                // ADDR_NONCE_HI case re-asserts it on every cycle in between --
                // hundreds of bus_clk cycles over a bit-banged GPIO bus. It was
                // written for an idempotent target (clearing a level), which it
                // is; a toggle is not. Flipping once per cycle would give the
                // clk_h side hundreds of ack edges for one host read, and it
                // would pop and discard a FIFO entry for each.
                //
                // nonce_valid_reg self-clears on the first of those cycles, so
                // this fires exactly once per nonce actually consumed. It also
                // means a read of NONCE_HI with nothing pending cannot ack.
                nonce_ack_toggle_bus <= ~nonce_ack_toggle_bus;
            end
        end
    end

    assign hash_active_bus  = hash_active_sync2_bus;
    assign nonce_valid_bus  = nonce_valid_reg;
    assign golden_nonce_bus = golden_nonce_reg;
    assign gpio_irq         = nonce_valid_reg;

endmodule
