// stub_wrapper_deps.v -- just enough to elaborate odocrypt_gpio_wrapper in a
// simulator, so the BUS FSM can be tested.
//
// These stand in for the three things that make the wrapper otherwise
// unsimulable outside Vivado: the 15,548-line autogenerated cipher, the hash
// core built on it, and a Xilinx hard macro. None of them participate in the
// register decode, which is what tb_bus_write exercises.
//
// WORTH THE TWENTY LINES. Every other bench in this tree tests a leaf module
// and passes, while a total failure of the UART write path sat in the
// wrapper's S_WRITE because nothing instantiated it. This file is the reason
// that gap is now closable.

`timescale 1ns / 1ps

// The host-facing block shifter. The bus FSM only ever strobes it.
module odo_block_data (
    input  wire         clk_h,
    input  wire [31:0]  data_from_host_in,
    input  wire         get_midstate_in,
    input  wire         get_block_in,
    input  wire         get_target_in,
    output wire [607:0] header,
    output wire [255:0] target
);
    assign header = 608'h0;
    assign target = 256'h0;
endmodule

// The hash core. Never finds anything here, which is what we want: the bus
// tests must not race a find.
// Port list and parameter name copied from the real module: INONCE, and
// (clk, header, target, nonce, found). Getting these wrong is how a stub
// silently stops standing in for the thing it replaces.
module miner_pipelined (clk, header, target, nonce, found);
    parameter INONCE = 0;
    input  wire         clk;
    input  wire [607:0] header;
    input  wire [255:0] target;
    output wire [31:0]  nonce;
    output wire         found;

    assign nonce = 32'h0;
    assign found = 1'b0;
endmodule

// Xilinx XADC. Returns a plausible temperature code so the fan block sees
// something sane, and never asserts DRDY.
module XADC #(
    parameter [15:0] INIT_40 = 0, INIT_41 = 0, INIT_42 = 0, INIT_43 = 0,
    parameter [15:0] INIT_44 = 0, INIT_45 = 0, INIT_46 = 0, INIT_47 = 0,
    parameter [15:0] INIT_48 = 0, INIT_49 = 0, INIT_4A = 0, INIT_4B = 0,
    parameter [15:0] INIT_4C = 0, INIT_4D = 0, INIT_4E = 0, INIT_4F = 0,
    parameter [15:0] INIT_50 = 0, INIT_51 = 0, INIT_52 = 0, INIT_53 = 0,
    parameter [15:0] INIT_54 = 0, INIT_55 = 0, INIT_56 = 0, INIT_57 = 0,
    parameter [15:0] INIT_58 = 0, INIT_5C = 0,
    parameter SIM_DEVICE = "7SERIES", parameter SIM_MONITOR_FILE = ""
) (
    output [15:0] DO,
    output        DRDY,
    output [7:0]  ALM,
    output        OT, BUSY,
    output [4:0]  CHANNEL,
    output        EOC, EOS,
    output        JTAGBUSY, JTAGLOCKED, JTAGMODIFIED, MUXADDR,
    input  [6:0]  DADDR,
    input         DCLK, DEN,
    input  [15:0] DI,
    input         DWE, RESET,
    input  [15:0] VAUXN, VAUXP,
    input         VN, VP, CONVST, CONVSTCLK
);
    assign DO   = 16'ha700;     /* ~56 C, in the band the fan curve expects */
    assign DRDY = 1'b0;
    assign ALM  = 8'h0;
    assign OT   = 1'b0;
    assign BUSY = 1'b0;
    assign CHANNEL = 5'h0;
    assign EOC = 1'b0;
    assign EOS = 1'b0;
    assign JTAGBUSY = 1'b0;
    assign JTAGLOCKED = 1'b0;
    assign JTAGMODIFIED = 1'b0;
    assign MUXADDR = 1'b0;
endmodule
