/*
 * gen_encrypt_vector -- produce the (plaintext, ciphertext) pair that
 * sim/tb_encrypt_oracle.v compares encrypt.v against.
 *
 * WHY THIS FILE EXISTS NOW
 *
 * tb_encrypt_oracle.v says "The vector is generated by
 * tools/gen_encrypt_vector.c and pasted below" -- and that file was never
 * committed. So the one testbench in the suite that compares the RTL against
 * SOFTWARE could not be refreshed when the epoch rolled. Its vector is pinned
 * to epoch 1787616000 while the shipped encrypt.v is 1788480000, so it fails
 * for a reason that has nothing to do with correctness, and it is not wired
 * into run_all_sims.sh either. In practice that means the cipher has not been
 * checked against software since the epoch changed.
 *
 * Every other testbench compares RTL against RTL and is blind to a fault
 * present in both cores.
 *
 * SELF-VALIDATION
 *
 * Run with no arguments and it first reproduces the EXISTING vector pair at
 * epoch 1787616000. That pair was generated independently and pasted into the
 * testbench, so reproducing it proves this program's byte ordering matches
 * what the testbench and the RTL agree on. Only then does it emit a fresh pair
 * for the current epoch. If the self-check fails, the ordering is wrong and
 * the emitted vector would be worthless -- so it refuses to emit one.
 *
 * BUILD
 *   gcc -O2 -I<odo-miner-cyclonev>/hps -o gen_encrypt_vector \
 *       gen_encrypt_vector.c <odo-miner-cyclonev>/hps/odocrypt_state.c
 */

#include "odocrypt_state.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

#define BLOCK 80

/* The testbench's 640-bit literal, most significant hex digit first.
 *
 * BYTE ORDER IS REVERSED against the literal: block byte 0 is the LEAST
 * significant byte of the 640-bit value, i.e. little-endian, the same
 * convention the 80-byte header uses everywhere else in this project. That is
 * not documented anywhere and was established by trying all four
 * byte/bit-order combinations against the known pair below -- exactly one
 * matches, which is why the self-check is worth keeping. */
static const char VEC_IN_HEX[] =
    "00000000b16a45338345e0bfeaf7c2a05a432f210e50525619f8ea60e031a5b8"
    "1235dd2e7e1ebb795f0ef696012ab25cccfc28e42cfc30cacd56cf5b2e32522f"
    "8513b1c66d0c322fdfe388ca6969f7a5";

static const char VEC_OUT_HEX[] =
    "36c339a46792f34a5316a8477df1828c2b0776a99e13df493c805599ce99127b"
    "34e0ae6e53c6497b21e0dce108695430f52ca79409234ae9c544bcb1ae036464"
    "e28a0933e0e5283c3e8a110d0f08ce8d";

static int hex2block(const char *hex, uint8_t out[BLOCK])
{
    if (strlen(hex) != BLOCK * 2)
        return -1;
    for (int i = 0; i < BLOCK; i++) {
        unsigned v;
        if (sscanf(hex + 2 * i, "%2x", &v) != 1)
            return -1;
        out[BLOCK - 1 - i] = (uint8_t)v;   /* see the note on byte order */
    }
    return 0;
}

static void print_literal(const char *name, const uint8_t b[BLOCK])
{
    printf("    localparam [639:0] %s = 640'h", name);
    for (int i = BLOCK - 1; i >= 0; i--)
        printf("%02x", b[i]);
    printf(";\n");
}

int main(int argc, char **argv)
{
    uint32_t key = (argc > 1) ? (uint32_t)strtoul(argv[1], NULL, 0)
                              : 1788480000u;

    odo_epoch_state_t st;
    uint8_t in[BLOCK], out[BLOCK], want[BLOCK];

    /* ---- self-check against the pair already in the testbench ---------- */
    if (hex2block(VEC_IN_HEX, in) || hex2block(VEC_OUT_HEX, want)) {
        fprintf(stderr, "built-in vector is malformed\n");
        return 2;
    }
    odo_epoch_generate(&st, 1787616000u);
    odo_encrypt(&st, in, out);

    if (memcmp(out, want, BLOCK) != 0) {
        fprintf(stderr,
            "SELF-CHECK FAILED at epoch 1787616000.\n"
            "  This program does not reproduce the vector already pasted into\n"
            "  tb_encrypt_oracle.v, so its byte ordering does not match the\n"
            "  testbench and the RTL. Refusing to emit a vector.\n\n");
        fprintf(stderr, "  want ");
        for (int i = 0; i < BLOCK; i++) fprintf(stderr, "%02x", want[i]);
        fprintf(stderr, "\n  got  ");
        for (int i = 0; i < BLOCK; i++) fprintf(stderr, "%02x", out[i]);
        fprintf(stderr, "\n");
        return 1;
    }
    fprintf(stderr, "self-check OK: reproduces the epoch 1787616000 vector\n");

    /* ---- emit a fresh pair for the requested epoch --------------------- */
    /* Same plaintext, so a diff against the old vector shows only the effect
     * of the epoch. Nonce 0 in the top 32 bits, as the RTL presents it. */
    odo_epoch_generate(&st, key);
    odo_encrypt(&st, in, out);

    printf("    // ---- vector, from the software oracle at epoch %u"
           " -------------\n", (unsigned)key);
    printf("    // Regenerate with:  gen_encrypt_vector %u\n", (unsigned)key);
    print_literal("VEC_IN ", in);
    print_literal("VEC_OUT", out);
    return 0;
}
